### ISSUE TITLE
Split Tests in partial classes

### ISSUE THREAD

**Issue by srasch** [System-IO-Abstractions/System.IO.Abstractions#113]
I would like to split some testclasses to some smaller classes (partials). One partial class for one method. Right now, there is one file "MockFileTests.cs" with ~1700 loc.

I think, it would be great to split them up and do it like this:

```
TestHelper.Tests (project)
  -- MockFileTests (folder)
      -- MockFileTests.Copy.cs
      -- MockFileTests.Move.cs
```

What do you think?

**Comment by tathamoddie** [comment]
I agree with splitting the tests out.

I don't think they need to be partials.

Let's just use:

    TestHelper.Tests (project)
      -- MockFileTests.cs
      -- MockFileCopyTests.cs
      -- MockFileMoveTests.cs

That gives us:

* shorter files
* right click > Add Class still works
* file names map to class names which map to what you see in test runners

As opposed to people having to muck around with manually changing the class definition if they want to test a new area.

**Comment by srasch** [comment]
alright, I'm going to split them out. Some tests (one or two per method) I won't pull out, but let them in MockFileTests.

**Comment by jpreese** [comment]
Closing, this has been merged.
