### ISSUE TITLE
Add dotnetcore support

### ISSUE THREAD

**Issue by gavynriebau** [System-IO-Abstractions/System.IO.Abstractions#148]
Now the first release candidate is out it'd be great if [dotnetcore](http://dotnet.github.io/) support could be added in preparation for the first RTM release.

Reading through #25 I noticed the whole issue surrounding corefx and filesystem testability has already been discussed in dotnet/corefx#312. It looks like at some point they're going to redesign the filesystem related framework classes.

This might take some time so until then it'd be good if System.IO.Abstractions could support dotnetcore.

**Comment by lvermeulen** [comment]
@tathamoddie @gavynriebau  I needed a netcore version as well so I ported it. Like @gavynriebau I don't have the time to take ownership so I can either submit a PR or fork System.IO.Abstractions.netcore and have that on github & nuget. I want to be polite about this, so can you please let me know how you would prefer that I proceed?

**Comment by ericnewton76** [comment]
I would recommend to go ahead and submit the PR, with some notation that
you can't take ownership.

Others (like me) can then inspect the changes, fork from yours and make the
rest of the changes/integrations and then submit a new PR back to the
master.  We'd reference yours to say something like "Closes PR 555 as well"

**Comment by borismod** [comment]
I am also interested on .NET Core support. Is there any update of this?

**Comment by jpreese** [comment]
Closing. Now supported.
