### ISSUE TITLE
Implement custom MockPath.GetDirectoryName

### ISSUE THREAD

**Issue by manne** [System-IO-Abstractions/System.IO.Abstractions#154]
because it can actually hit the disk (internally calls `Path.GetFullPath`).

**Comment by ericnewton76** [comment]
@jpreese was this addressed somewhere? seems like a legit issue although I can't imagine why Path.GetFullPath would hit the disk

**Comment by jwallet** [comment]
on unix system this is what I get cause `GetDirectoryName` returns `""`
It needs to have a proper implementation so it will return the same result on both OS.

```
System.ArgumentException : The path is not of a legal form.
Parameter name: path
Stack Trace:
   at System.IO.Abstractions.TestingHelpers.MockPath.GetFullPath (System.String path)
```

`var folderPath = _fileSystem.Path.GetDirectoryName(@"C:\path\file.mp3")`
this was used to check if the directory is empty after deleting `file.mp3` like so `!_fileSystem.Directory.EnumerateFiles(folderPath).Any()`
