### ISSUE TITLE
Is it possible to convert a FileInfoWrapper or FileInfo base into normal FileInfo

### ISSUE THREAD

**Issue by oleguerOrtega** [System-IO-Abstractions/System.IO.Abstractions#155]
I need to pass a file info to an external library. If I use the factory I get a FileInfoWrapper but I need the normal FileInfo. there is a reason why the instance is private? Could we make it protected so I can extended? or can we implement an accesor to it?

**Comment by fgreinacher** [comment]
Can’t you just new up a `FileInfo` with that path exposed by the wrapper?

**Comment by jpreese** [comment]
@oleguerOrtega based on the age of this ticket, I'm going to close this out. If this does not answer your question, please feel free to reopen or create a new one.
