### ISSUE TITLE
MockDirectoryInfo implement LastWriteTimeUtc

### ISSUE THREAD

**Issue by johncmckim** [System-IO-Abstractions/System.IO.Abstractions#156]
I need to use LastWriteTimeUtc on MockDirectoryInfo which is not implemented. Could this be implemented please?

**Comment by tathamoddie** [comment]
Hi! The best route to an implementation is a pull request with tests. Shout out if you need help.

**Comment by johncmckim** [comment]
No worries. I'll put something together.

**Comment by jpreese** [comment]
To be resolved by #311

**Comment by jpreese** [comment]
#311 has been merged. Closing!
