### ISSUE TITLE
Store IFileSystem to FileSystemInfoBase in order to Create Files and Directories

### ISSUE THREAD

**Issue by mamuesgit** [System-IO-Abstractions/System.IO.Abstractions#158]
I can create a FileInfoBase / DirectoryInfoBase during runtime only from IFileSystem. 

If that IFileSystem object would be stored in the FileSystemInfoBase while creating (like `fileSystem.DirectoryInfo.FromDirectoryName()` we could create subfolders / files based on given DirectoryInfoBase later:
`DirectoryInfoBase subDir = rootDir.CreateSubDirectory("subDirName)`

**Comment by jpreese** [comment]
I'm not quite sure I understand the question, @mamuesgit. Though given this is quite old I'm going to close this. If this is still an outstanding problem for you, please do not hesitate to reopen this ticket or create another one.
