### ISSUE TITLE
help using the FileSystemWatcherWrapper in UnitTets

### ISSUE THREAD

**Issue by WarBorg** [System-IO-Abstractions/System.IO.Abstractions#161]
hello.

I am writing some unit tests and wanted to use the FileSystemWatcherWrapper to look at a dir to check if files are added or deleted, but the problem is even if I am using the FileSystemWatcherWrapper the events will be raised on changes to my real file system and I don't see any way to set a custom FileSystem to the Watcher, can you please tell me if this is possible? 

thank you in advance

**Comment by manne** [comment]
`FileSystemWatcherWrapper` should not be used in unit test, because it watches the real file system.
The corresponding implementation for unit tests is not implemented.

**Comment by jpreese** [comment]
Thanks for bringing this to our attention @WarBorg. We'll use #167 to track its progress.
