### ISSUE TITLE
Add events on major events

### ISSUE THREAD

**Issue by zvirja** [System-IO-Abstractions/System.IO.Abstractions#168]
Sometimes it's needed to test sequence of events with file system and currently it's impossible to do that with current implementation of `MockFileSystem`. Basically, we should add a couple of events, so we could subscribe on that events in our test. Moreover, this way we could simulate various situations (e.g. throw sharing violation exception when particular file is opened).

List of events:   
- File is being opened
- File is being created
- File is being deleted
- File is being updated
- File stream is opened
- File stream is closed
- Directory is being created
- Directory is being deleted

I could implement that and create a PR for you. Will you approve such kind of PR?
Do you see some other ways to achieve the desired behavior?

**Comment by manne** [comment]
@Zvirja which kind of API do you have in your mind? and can you give example(s).

**Comment by Zvirja** [comment]
For instance, that could be a public property exposed directly from the `MockFileSystem`:
```csharp
var fs = new MockFileSystem();
fs.Events.OnFileCreated += (sender, args) => {}
...
```

Basically, nothing special - any way it's convenient to implement. The only requirement is to be able to hook such events :)

Let me know if you want more input from me.

**Comment by manne** [comment]
I think we need an API for the project `TestingHelpers` (MockFileSystem).
Some pull requests/issues indicate the need for this API.
see #189, #177 & #183

**Comment by ericnewton76** [comment]
I wouldnt recommend events on the MockFileSystem at the moment.  

You're basically then implementing a FileSystemWatcher instead.  We should make sure the goal is parity with mscorlib.

**Comment by manne** [comment]
I prefer to have a FileSystemWatcher.
@Zvirja is a FileSystemWatcher sufficient for your purpose?

**Comment by Zvirja** [comment]
I'm not sure that watcher could cover my initial need why I fired this issue. Initially I wanted to have a way to throw exception when file is opened. That will not be achieved by watcher as it doesn't provide us with appropriate event.

Also FileSystemWatcher isn't synchronous by itself (if I'm not mistaken) which also makes it more difficult to  simulate concurrency issues.

**Comment by rkoeninger** [comment]
I outlined an attempt to do this in #373 and it didn't go over well. It was agreed that this would be too involved for this library. I assume the same answer would apply to this issue.

**Comment by fgreinacher** [comment]
In my opinion adding synchronous events like described here would enable quite some scenarios, so I would not reject a PR in this direction.
