### ISSUE TITLE
Throw IOException on FileInfoBase.OpenRead()

### ISSUE THREAD

**Issue by dgee2** [System-IO-Abstractions/System.IO.Abstractions#170]
Hi,

I am trying to engineer a situation for a test case where a file cannot be opened when calling OpenRead on the FileInfoBase object. Is it possible to force an exception when opening it from a MockFileSystem? I have looked into opening the file using OpenWrite and then trying to open it again using OpenRead but this didn't seem to work:

```
var fileSystem = new MockFileSystem(new Dictionary<string, MockFileData> {
    { @"C:\temp\tempFile.txt", MockFileData.NullObject }
};

var file = fileSystem.FileInfo.FromFileName(@"C:\temp\tempFile.txt");

using (var writeLock = fileSystem.File.OpenWrite(@"C:\temp\tempFile.txt")){
    file.OpenRead();
}
```

If anyone could think of another way to make OpenRead throw an IOException or if there is a way to mock the FileInfo that I am creating for file, it would be greatly appreciated.

Thanks

**Comment by Mike-EEE** [comment]
I am looking for exactly the same thing.  Any luck with this?

**Comment by AlexanderPruss** [comment]
Yeah, I need this as well. I'll add a fork for it hopefully sometime today.

**Comment by AlexanderPruss** [comment]
Added a PR - https://github.com/tathamoddie/System.IO.Abstractions/pull/180

**Comment by Mike-EEE** [comment]
Nice work, @AlexanderPruss!  Thank you for contributing to the community.  FWIW, I ended up using @kzu's excellent [Moq framework](https://github.com/moq/moq) to get the behavior that I was after. 😄

**Comment by AlexanderPruss** [comment]
@Mike-EEE Does the Moq Framework allow mocking of MSCORLIB classes?

**Comment by Mike-EEE** [comment]
@AlexanderPruss yes you can Moq any interface and any class as long as the member you are mocking is virtual/overridable.  That is, interfaces are completely 100% mockable, and overridable/virtual methods and members in classes are mockable.

**Comment by AlexanderPruss** [comment]
Removed my PR, I'm going to merge the 7+ bug fixes I've made onto my master branch.

**Comment by jpreese** [comment]
@Mike-EEE @AlexanderPruss @dgee2 -- this has been merged into master and is available as of the latest release.
