### ISSUE TITLE
Consider API Adjustment to Use Interfaces Rather Than Abstract Classes

### ISSUE THREAD

**Issue by Mike-EEE** [System-IO-Abstractions/System.IO.Abstractions#175]
Cool project. :)  Thank you for keeping it current.

Checking this out just now.  It appears there are files such as `DirectoryInfoBase` and `FileInfoBase`.  Has there been any thought towards making these interfaces instead, So `IDirectoryInfo` and `IFileInfo`?  That way we're really abstracting the goodness and don't have to pass implementations around.

Thank you for any consideration!

**Comment by DavidArno** [comment]
Just found a link to this, looked at the code and saw the same thing and thought the same thing.

This could be a really good project, but it's difficult to take it seriously when it used abstract classes and inheritance, rather than interfaces. I'm happy to fix and do a PR if you'd like?

**Comment by MCCoolMoDAue** [comment]
I looked at some classes, and mostly the abstract classes are unnecessary.
Introducing interfaces should be straight forward.

**Comment by fgreinacher** [comment]
Implemented by #452
