### ISSUE TITLE
Assembly signed

### ISSUE THREAD

**Issue by ianselmi** [System-IO-Abstractions/System.IO.Abstractions#178]
Hi, from version 2.0.0.124 the assembly signed is missing in nuget package assembly.

Can you resign the assembly? In my project my assembly are all signed and I can't installed new updates

Thanks

**Comment by AlexanderPruss** [comment]
https://github.com/tathamoddie/System.IO.Abstractions/pull/182

**Comment by MCCoolMoDAue** [comment]
The System.IO.Abstractions.dll in the package version 138 is still unsigned.
Is this supposed to be like that?
Maybe I am understanding wrong?

**Comment by jpreese** [comment]
As of v2.1.x.x the package should be signed.
