### ISSUE TITLE
FileInfo.MoveTo() shouldn't throw exceptions when moving a mocked file to itself

### ISSUE THREAD

**Issue by AlexanderPruss** [System-IO-Abstractions/System.IO.Abstractions#181]
See the discussion here: http://stackoverflow.com/questions/40722205/should-mscorlibs-fileinfo-moveto-throw-an-exception-if-trying-to-move-a-file

I'm in the process of binding System.IO.Abstractions into an existing project. One of my tests just started failing, namely one in which a file is moved to itself. It turns out that Microsoft's FileInfo allows a file to move to itself, even though [the documentation](https://msdn.microsoft.com/en-us/library/system.io.fileinfo.moveto(v=vs.110).aspx) appears to suggest this is illegal. System.IO.Abstraction's MockFile, however, checks to see if the file exists, and always throws an exception if it does.

I think it's more important to match mscorlib's actual implementation than their documentation; as such, I'd like MockFileInfo.MoveTo() to call CopyTo() with the overwrite flag set to true.

**Comment by AlexanderPruss** [comment]
https://github.com/tathamoddie/System.IO.Abstractions/pull/183

**Comment by AlexanderPruss** [comment]
Another difference between the Mock implementation and mscorlib is that the mock implementation doesn't throw an exception when trying to move or copy a nonexistent file. I'll add that to the PR as well I guess.

**Comment by ericnewton76** [comment]
Regarding a file is moved to itself issue, you're 100% correct in that MockFileSystem should mimic mscorlib behavior.  

And that's a great catch that the MockSystem wasn't throwing an exception for a file that didnt already exist.

**Comment by AlexanderPruss** [comment]
I'm going through and converting loads of legacy C# IO test code to use this library, so I'm finding lots of edge cases :)

**Comment by jpreese** [comment]
#299 will resolve this.
