### ISSUE TITLE
Read-only mocked files should not be deletable.

### ISSUE THREAD

**Issue by AlexanderPruss** [System-IO-Abstractions/System.IO.Abstractions#184]
See https://msdn.microsoft.com/en-us/library/system.io.file.delete(v=vs.110).aspx

A read-only mock should throw an UnauthorizedAccessException if it gets deleted.

**Comment by AlexanderPruss** [comment]
https://github.com/tathamoddie/System.IO.Abstractions/pull/185

**Comment by jpreese** [comment]
Should be a pretty straightforward merge. Looking into this one soon.

**Comment by jpreese** [comment]
Confirmed it's an issue -- will be handled in #303. Thanks for finding this, @AlexanderPruss !

**Comment by tathamoddie** [comment]
Fixed by 370052d
