### ISSUE TITLE
Directory.Move() throws exceptions when trying to move a file, not a directory.

### ISSUE THREAD

**Issue by AlexanderPruss** [System-IO-Abstractions/System.IO.Abstractions#187]
Directory.Move() should be able to move files: https://msdn.microsoft.com/en-us/library/system.io.directory.move(v=vs.110).aspx

The current implementation of MockDirectory, however, assumes that the moved object is a directory and throws an exception.

System.IO.Abstractions.TestingHelpers.dll!System.IO.Abstractions.TestingHelpers.MockDirectory.EnumerateDirectories(string path, string searchPattern, System.IO.SearchOption searchOption)
System.IO.Abstractions.TestingHelpers.dll!System.IO.Abstractions.TestingHelpers.MockDirectory.GetDirectories(string path, string searchPattern, System.IO.SearchOption searchOption)
System.IO.Abstractions.TestingHelpers.dll!System.IO.Abstractions.TestingHelpers.MockDirectory.GetDirectories(string path, string searchPattern) 
System.IO.Abstractions.TestingHelpers.dll!System.IO.Abstractions.TestingHelpers.MockDirectory.GetDirectories(string path)
System.IO.Abstractions.TestingHelpers.dll!System.IO.Abstractions.TestingHelpers.MockDirectory.Move(string sourceDirName, string destDirName)

**Comment by AlexanderPruss** [comment]
Yet another PR: https://github.com/tathamoddie/System.IO.Abstractions/pull/188

**Comment by fgreinacher** [comment]
This is released with https://github.com/System-IO-Abstractions/System.IO.Abstractions/releases/tag/v3.1.1
