### ISSUE TITLE
There should be a way to define illegal drives for the MockFileSystem

### ISSUE THREAD

**Issue by AlexanderPruss** [System-IO-Abstractions/System.IO.Abstractions#189]
The MockFileSystem does not throw an exception when trying to create a directory in a nonexistent drive. 

This is a somewhat more difficult request because we obviously want to separate the test setup of the mock filesystem from its actual execution, and at the moment both usecases run through the same function, namely MockFileSystem.AddDirectory().

**Comment by AlexanderPruss** [comment]
I thought this would break old tests, but ended up doing a different, easier solution - https://github.com/AlexanderPruss/System.IO.Abstractions---Consistency-with-MSCORLIB-fixes/pull/6

The MockFileSystem on my fork can now receive a list of "Forbidden Directories", which are checked against when creating new directories. So if you want to simulate "A:\\" not being mapped, simply call fileSystem.AddForbiddenDirectory("A"). 

Unfortunately, I ended up merging all my other fixes to my master branch, so it will annoying to create a PR  just to fix this issue. But you can always just merge all my fixes in one go :)

**Comment by ericnewton76** [comment]
I don't think this makes sense, you want to "add forbidden directories" but in theory, wouldn't all nonexistent drives be forbidden from the start?  So would a "CreateDrive" method make more sense, to deal with your specific example of A:\ not existing?

Secondly, this feels like an edge case rooted in reality of filesystems, and not in the mocking of testing your libraries.  As in, whats the point of testing that *your* library throws a FileNotFoundException when you try to open a file that doesn't exist?  The responsibility of that scenario is in the *base* library implementation and testing, not your library's test implementation.  Also meaning, test your code not others.

Perhaps I'm wrong but this is a code smell I think.

**Comment by manne** [comment]
The suggestion to create a method `MockFileSystem.CreateDrive` makes more sense to me.
Then the behavior to create files/directories of the MockFileSystem on a non existing drive has to change, it should result in an exception. This would be a breaking change.

**Comment by AlexanderPruss** [comment]
@ericnewton76 Unfortunately, the MockFileSystem currently assumes that all drives have already been created; reversing this design decision would break existing test code. I'm also not sure why you think this is me testing the wrong library (?) - the MSCORLIB library does, in fact, throw an exception if accessing a nonexistent drive.

@manne I ended up doing it this way in order to avoid breaking changes. Ideally, we would have setup methods in the MockFileSystem that don't perform the drive check, but as discussed in https://github.com/tathamoddie/System.IO.Abstractions/issues/194, the API for the MockFileSystem ends up using the same internal methods as calls to the mocked filesystem, which makes this difficult.
