### ISSUE TITLE
File.Move unhelpful DirectoryNotFoundException message

### ISSUE THREAD

**Issue by harrybellamy** [System-IO-Abstractions/System.IO.Abstractions#196]
When attempting to move a file to a location that doesn't exist gives the following unhelpful error message:

Could not find a part of the path 'System.IO.Abstractions.TestingHelpers.MockDirectoryInfo'.

**Comment by jpreese** [comment]
@harrybellamy I just ran this case on the latest release, and I am getting the message:

```
Message: System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\a'.
```

using the test case

```csharp
        [Test]
        public void Test()
        {
            var fs = new MockFileSystem();
            fs.AddFile(@"C:\src.txt", MockFileData.NullObject);
            fs.File.Move(@"C:\src.txt", @"C:\a\dest.txt");
        }
```

If this is still an issue for you, please do not hesitate to reopen the ticket.
