### ISSUE TITLE
Specifying MockFileData Length

### ISSUE THREAD

**Issue by robertlarkins** [System-IO-Abstractions/System.IO.Abstractions#197]
I'm using the TestingHelpers to mock a `FileInfoBase`, so I've created a `MockFileSystem` and added a `MockFileData` to it. I'm wanting to test some code that has logic based on file size (`FileInfoBase.Length`). But it appears that I can only change the `Length` property by setting the `Contents` property.

Is it possible to mock a file that is reasonably large (over 1gb), without having to set the contents?

**Comment by manne** [comment]
No, without modification it is not possible.

**Comment by jpreese** [comment]
I don't think we need to do this. While yes, you can't directly modify the Length property, you can set it through the Contents property.

```csharp
            var fileSystem = new MockFileSystem(new Dictionary<string, MockFileData>
            {
                {XFS.Path(@"c:\a.txt"), new MockFileData("".PadRight(42))}
            });
            var file = fileSystem.FileInfo.FromFileName(@"c:\a.txt"); // file.Length is 42
```

**Comment by robertlarkins** [comment]
Would you still recommend doing it this way for mocking files that are gigabytes in size? A 1gb file would be `"".PadRight(1000000000)`.

**Comment by stogle** [comment]
@jpreese I'm facing the same issue. I want to test code that rejects very large files, and I don't want to create gigabytes of dummy content in my test. It would be acceptable if any methods that tried to access the contents of the mock file threw an exception, as long as the length was reported correctly.
