### ISSUE TITLE
MockFileSystem Directory.Exists doesn't work if directory is empty

### ISSUE THREAD

**Issue by XtraKrispi** [System-IO-Abstractions/System.IO.Abstractions#200]
If I create an empty directory:

`
var fakeFileSystem = new MockFileSystem(new Dictionary<string, MockFileData>
            {
                { @"C:\TestDirectory", new MockDirectoryData() }
            });
`

And then need to do a 
`
fakeFileSystem.Directory.Exists(@"C:\TestDirectory")
`

The Exists returns false, and if we try to create the directory we get:
System.IO.IOException: Cannot create "C:\TestDirectory" because a file or directory with the same name already exists

So it's in the internal file system, but the Exists method doesn't see it.  If we create a file within the directory, Exists works fine

**Comment by cmeeren** [comment]
I'm getting errors when I make mock directories without the trailing slash. What happens when you use `@"C:\TestDirectory\"` instead of `@"C:\TestDirectory"`?

**Comment by XtraKrispi** [comment]
Seems to work if I put a trailing slash... I can't remember anymore why we weren't using the trailing slash, but I'll definitely check

**Comment by cmeeren** [comment]
Probably related to #208 then.

**Comment by XtraKrispi** [comment]
Yeah, seems like it

**Comment by jpreese** [comment]
@XtraKrispi and @cmeeren -- I'm going to close this in favor of #208 as it is indeed the same issue. Let's continue the discussion there and try and get this hashed out.
