### ISSUE TITLE
Add the original System.IO documentation to all methods

### ISSUE THREAD

**Issue by cmeeren** [System-IO-Abstractions/System.IO.Abstractions#203]
As far as I can see, most methods have no documentation. It's too much hassle for me to manually look up the equivalent System.IO documentation all the time, and it also effectively disables the static exception analysis plugin for R# that I'm using, which relies on documented exceptions.

I realize that interfaces cannot enforce documented exceptions and behavior, but since this library is intended for mocking System.IO and not for creating alternative file system implementations, I think it would be a great idea to include the original documentation for all relevant methods, just like [Thinktecture.Abstractions](https://github.com/PawelGerr/Thinktecture.Abstractions).

**Comment by cmeeren** [comment]
Let me know if you want me to have a look at making a PR for this. It would mostly be to add `<inheritdoc>` tags to all interfaces/abstract classes, e.g.

````c#
public abstract class FileInfoBase : FileSystemInfoBase
{
    /// <inheritdoc cref="FileInfo.AppendText"/>
    public abstract StreamWriter AppendText();
````

![capture](https://cloud.githubusercontent.com/assets/7766733/23653149/c2adb946-032b-11e7-80a8-10d4c26cb020.PNG)

**Comment by Gusdor** [comment]
That would work great if one is using resharper. I am not and only a fraction of my team do. Personally, I would prefer to have concrete comments, rather than inheritance.

**Comment by jpreese** [comment]
I would agree that we wouldn't want a resharper specific implementation. I'm going to close this issue in favor of #245 as they both intend to achieve the same goal.
