### ISSUE TITLE
MockFileSystem should not require trailing slash for directories

### ISSUE THREAD

**Issue by cmeeren** [System-IO-Abstractions/System.IO.Abstractions#208]
Create a `MockFileSystem` with a directory that does not have a trailing slash:

````c#
var fs = new MockFileSystem(new Dictionary<string, MockFileData>
    {
        { @"C:\test1\test1.txt", MockFileData.NullObject },
        { @"C:\test2", new MockDirectoryData() }
    });

fs.File.Copy(@"C:\test1\test1.txt", @"C:\test2\test2.txt");
````

Running this code produces the following exception:

````
System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\test2\test2.txt'.
   at System.IO.Abstractions.TestingHelpers.MockFile.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.Abstractions.TestingHelpers.MockFile.Copy(String sourceFileName, String destFileName)
````

Adding a trailing slash to the folder definition fixes the problem:

````c#
...
        { @"C:\test2\", new MockDirectoryData() }
...
````

Now it runs successfully.

Using a trailing slash should not be necessary (`MockDirectoryData` should suffice to identify this as a folder).

**Comment by cmeeren** [comment]
I suppose the fix would be somewhere in AddFile (https://github.com/tathamoddie/System.IO.Abstractions/blob/master/TestingHelpers/MockFileSystem.cs#L97), but I don't fully understand how it works. I can make a PR if anyone can point me in the right direction.

**Comment by cmeeren** [comment]
Please see the image. Notice that when adding a directory without trailing slash, the trailing slash is not added during the MockFileSystem instantiation process. I expect this causes bugs to occur further down the line for code that assumes all directories should end with a slash, such as `File.Copy` and perhaps also `Directory.Exists` (#200).

![capture](https://cloud.githubusercontent.com/assets/7766733/23653868/66bc0fd6-032e-11e7-95f5-1691a1a7626d.PNG)

**Comment by nguyendangdung** [comment]
This is a bug
MockFileSystem allow creating both "C:\test\dir\" as a directory and "C:\test\dir" as a file. We know the true that it is impossible to exist both a directory and a file with a same name in a directory

**Comment by jpreese** [comment]
@nguyendangdung and @cmeeren At first glance, I'm not quite convinced it's a bug. Under the hood it's using GetDirectoryName, and as shown in the documentation (https://msdn.microsoft.com/en-us/library/system.io.path.getdirectoryname(v=vs.110).aspx) that is the expected behavior.

```
In most cases, the string returned by this method consists of all characters in the path up to but not including the last DirectorySeparatorChar or AltDirectorySeparatorChar. If the path consists of a root directory, such as "c:\", null is returned. Note that this method does not support paths using "file:". Because the returned path does not include the DirectorySeparatorChar or AltDirectorySeparatorChar, passing the returned path back into the GetDirectoryName method will result in the truncation of one folder level per subsequent call on the result string. For example, passing the path "C:\Directory\SubDirectory\test.txt" into the GetDirectoryName method will return "C:\Directory\SubDirectory". Passing that string, "C:\Directory\SubDirectory", into GetDirectoryName will result in "C:\Directory".
```
