### ISSUE TITLE
Add AllLeaves to MockFileSystem

### ISSUE THREAD

**Issue by cmeeren** [System-IO-Abstractions/System.IO.Abstractions#209]
My testing would be simplified if I had access to an array of only the "leaves" of the file system (all the files, as well as empty folders).

For example, if `AllPaths` contain

````
C:\
C:\foo\
C:\bar\
C:\bar\baz\
C:\bar\baz\test1.txt
C:\bar\baz\test2.txt
````

then I would expect `AllLeaves` to contain

````
C:\foo\
C:\bar\baz\test1.txt
C:\bar\baz\test2.txt
````

Here's a quick and dirty implementation I made for testing, using LINQ:

````c#
private string[] AllLeaves(MockFileSystem fs)
{
    Func<string, bool> isNotStartOfAnotherPath =
        path => !fs.AllPaths.Any(otherPath => otherPath.StartsWith(path) && otherPath != path);

    return fs.AllPaths.Where(isNotStartOfAnotherPath).ToArray();
}
````

**Comment by tathamoddie** [comment]
Isn't that covered by the system-defined `GetFileSystemEntries` method?

`Directory.GetFileSystemEntries(@"c:\temp", "*", SearchOption.AllDirectories)`

Doco: https://msdn.microsoft.com/en-us/library/dd383460(v=vs.110).aspx

This is covered in our wrappers too: https://github.com/tathamoddie/System.IO.Abstractions/blob/master/System.IO.Abstractions/DirectoryWrapper.cs#L99

**Comment by cmeeren** [comment]
No, it's not the same. `GetFileSystemEntries()` requires you to at least specify a drive, which is a problem if the mock filesystem contains multiple drives or network locations.

Here's an example of a test where I would like AllLeaves:

````c#
[Test]
public void CreateDirectories_Should_CreateNonExistentDirectories()
{
    var beforeOperation = new[]
        {
            @"C:\path\to\temp\dir\",
            @"C:\path\to\other\dir\test.txt",
            @"C:\test\"
        };

    // No trailing slashes due to #210
    var directoriesToCreate = new[]
        {
            @"C:\path\to\temp\dir",
            @"C:\path\to\other\dir",
            @"C:\test\foo\bar",
            @"\\some.network.location\G$\foobar\baz"
        };

    var expectedAfterOperation = new[]
        {
            @"C:\path\to\temp\dir\",
            @"C:\path\to\other\dir\test.txt",
            @"C:\test\foo\bar\",
            @"\\some.network.location\G$\foobar\baz\"
        };

   // Skipped: Create MockFileSystem
   // Skipped: Add files/folders from beforeOperation
   // Skipped: Instantiate unit under test and perform operation

    // Assert
    Assert.That(fs.AllLeaves, Is.EquivalentTo(expectedAfterOperation));
}
````

**Comment by cmeeren** [comment]
Created a PR now, I went for `AllNodes` as I think that's more correct. Also added tests for `AllPaths`, `AllFiles` and `AllDirectories` as I didn't see any.

As you probably can see, `AllNodes` represents new functionality that can ease testing: You create a `MockFileSystem` with some nodes, you perform some action on the file system, and then check the nodes again in the new state of the file system.

**Comment by cmeeren** [comment]
On second thought, maybe "leaves" is a better term than "nodes", because AFAIK non-empty folders can also be nodes. I'm no expert on this. Let me know if you want me to rename "Nodes" to "Leaves".
