### ISSUE TITLE
Is FileStream covered?

### ISSUE THREAD

**Issue by THammond9** [System-IO-Abstractions/System.IO.Abstractions#224]
I need to be able to test a FileStream but I don't see anyway to do it with what it currently implemented. I see PR #177 but it hasn't been merged yet and the PR is 6 months old. I assume that FileStream is already covered in some way?

**Comment by bmcd77** [comment]
I'm, also looking to mock a FileStream and found this pull request but the implementation doesn't seem to be in the latest version on nuget as far as I can tell. Any update on when this support might be added?

**Comment by jpreese** [comment]
To be resolved by #177
