### ISSUE TITLE
MockFileSystem does not fail on File.Create when directory does not exists.

### ISSUE THREAD

**Issue by kaar** [System-IO-Abstractions/System.IO.Abstractions#227]
This should fail when directory for fileName does not exists.
This is not the case when using MockFileSystem
```cs
using (var file = fileSystem.File.Create(fileName)) {
}
```
On a real file system this thows.

**Comment by jpreese** [comment]
@kaar I just ran this test scenario on my local machine, and I am getting a DirectoryNotFoundException.

```csharp
        [Test]
        public void Test()
        {
            var fs = new MockFileSystem();
            fs.File.Create(@"C:\lol.txt");
        }
```
