### ISSUE TITLE
Exception is not thrown when filename with illegal character is passed to WriteAllBytes()

### ISSUE THREAD

**Issue by tonyseattle** [System-IO-Abstractions/System.IO.Abstractions#235]
Exception is not thrown when filename with illegal character is passed to WriteAllBytes()

mockFS = new MockFileSystem();
mockFS.AddDirectory(@"c:\");
mockFS.File.WriteAllBytes(@"c:\ab*cde.txt", new byte[100]);    // exception is expected.

**Comment by jpreese** [comment]
This has been resolved in that latest release. Thanks for finding this @tonyseattle !
