### ISSUE TITLE
MockFileInfo.CopyTo does not throw exception when source does not exist

### ISSUE THREAD

**Issue by AlenPelin** [System-IO-Abstractions/System.IO.Abstractions#243]
Call to `MockFileInfo.CopyTo (destination)` does not throw an exception when source file does not exist.

The following unit test fails:

```c#
[Test]
public void Test()
{
  var fs = new MockFileSystem();
  var oldPath = "C:\folder\file.txt";
  var newPath = "C:\newfolder\file.txt";
  var file = fs.FileInfo.FromFileName(oldPath);

  Assert.Throws<FileNotFoundException>(() => file.CopyTo(newPath));
}
```

**Comment by jpreese** [comment]
@AlenPelin looking at the System.IO documentation (https://msdn.microsoft.com/en-us/library/f0e105zt(v=vs.110).aspx), we shouldn't expect a FileNotFoundException. 

In your case, the exception would be a DirectoryNotFoundException which currently passes.

Also make sure your paths are prefixed with @ to ensure the paths are parsed correctly.
