### ISSUE TITLE
How can I create a FileSystemWatcher to monitor changes to an IFileSystem?

### ISSUE THREAD

**Issue by TAGC** [System-IO-Abstractions/System.IO.Abstractions#251]
I'm trying to create a class that monitors changes to the filesystem, but I'm not sure how I can create a `FileSystemWatcher` that monitors changes to an `IFileSystem` instance I inject to the class during construction.

I've looked at `FileSystemWatcherBase` and `FileSystemWatcherWrapper` but I haven't been able to figure it out. I'm just looking for a way to monitor changes (files being added/removed) to an instance of `IFileSystem` so that I can make my class testable.

[Related SO question](https://stackoverflow.com/questions/47031711/how-can-i-use-filesystemwatcher-from-system-io-abstractions-to-monitor-a-mock-fi).

**Comment by jpreese** [comment]
@TAGC FWIW, there's an open PR (#60) and another issue (#167) revolving around this question. It seems to be a pretty common request, so as we continue to flush through all of the issues and pull requests, we'll make sure to keep it on our radar.

**Comment by jpreese** [comment]
#60 has made this functionality possible. If this doesn't suit your needs please let us know and we can work towards a resolution.
