### ISSUE TITLE
MockFileSystem.AddFile/Directory causes TypeInitializationException on Unix platforms

### ISSUE THREAD

**Issue by TAGC** [System-IO-Abstractions/System.IO.Abstractions#252]
`MockFileSystem.AddFile` and `MockFileSystem.AddDirectory` create instances of `MockFileData`. When this type is first accessed on a Unix system, it causes `TypeInitializationException` to be thrown with this stack trace:

```
System.TypeInitializationException : The type initializer for 'System.IO.Abstractions.TestingHelpers.MockFileData' threw an exception.
[xUnit.net 00:00:01.6614320]       ---- System.PlatformNotSupportedException : Access Control List (ACL) APIs are part of resource management on Windows and are not supported on this platform.
```

This is probably because of [this line](https://github.com/tathamoddie/System.IO.Abstractions/blob/master/TestingHelpers/MockFileData.cs#L63) where you try instantiating a `FileSecurity` object.

Has this library even been tested on non-Windows platforms?

**Comment by TAGC** [comment]
For anyone else looking for a workaround, I discovered a library called [Xunit.SkippableFact](https://github.com/AArnott/Xunit.SkippableFact) that lets you selectively skip running tests (facts or theories) based on some condition(s).

In my case I annotated all my xUnit tests that use `System.IO.Abstraction` in any way with `SkippableFact`/`SkippableTheory`:

```cs
[SkippableTheory]
[MemberData(nameof(UsbDeviceExamples))]
internal void Dev_Monitor_Should_Ignore_Usb_Device_Events_When_Not_Enabled(UsbDevice device)
{
    // GIVEN the device monitor is disabled.
    _devMonitor.Enabled = false;

    // WHEN a USB device is connected and disconnected.
    SimulateUsbDeviceArrival(device);
    SimulateUsbDeviceRemoval(device);

    // THEN no evente should have been published.
    _usbEvents.ShouldBeEmpty();
}
```

In the unit test class constructor (which is xUnit's equivalent of `setup()` and runs at the start of each test) I added this:

```cs
public DevMonitorSpec()
{
    Skip.IfNot(RunningOnWindows, "See https://github.com/tathamoddie/System.IO.Abstractions/issues/252");

    // Rest of setup.
}
```

Where `RunningOnWindows` is defined as:

```cs
private static readonly bool RunningOnWindows = RuntimeInformation.IsOSPlatform(OSPlatform.Windows);
```

This allows me to run these tests locally on my development machine, but skips them during my Bitbucket Pipeline CI builds (which uses a Linux environment). It's not ideal but it suffices for the time being I guess.

**Comment by jpreese** [comment]
We are now skipping tests that will never pass on Linux environments (acls, drives, etc).
