### ISSUE TITLE
There is no equivalent of new DriveInfo(path) in IDriveInfoFactory

### ISSUE THREAD

**Issue by marcomeyer** [System-IO-Abstractions/System.IO.Abstractions#270]
Would be nice to have a method like `FromDriveName(path)` on `IDriveInfoFactory` which provides the functionality of the .NET Framework's `new DriveInfo(path) `.

Similar to e.g. `FromDirectoryName` on `IDirectoryInfoFactory`.

**Comment by jpreese** [comment]
This has been merged. Thanks @marcomeyer !
