### ISSUE TITLE
Assembly name of TestingHelpers

### ISSUE THREAD

**Issue by jbaehr** [System-IO-Abstractions/System.IO.Abstractions#271]
At least in the current `System.IO.Abstractions.TestingHelpers-2.1.0.178` the assembly itself is only named `TestingHelpers.dll`, i.e. no `System.IO.Abstractions` prefix. This is a inconsistency with the main `System.IO.Abstractions` and yells for name clashes: "TestingHelpers.dll" is quite generic.

Please consider naming the assembly `System.IO.Abstractions.TestingHelpers.dll` in future versions.

**Comment by jpreese** [comment]
Thanks for the clarification, I missed that. Changing the assembly shouldn't be a big deal and I don't really see a reason why not to. 

I agree TestingHelpers.dll could have a high possibility of clashing.

**Comment by tathamoddie** [comment]
I think it historically had the right assembly name, but the directory name was just shorter in source. When we moved to the more modern project system, I think we lost the assembly name override. D'oh.
