### ISSUE TITLE
Cannot set properties on DriveInfoBase objects returned by MockFileSystem.DriveInfo.GetDrives

### ISSUE THREAD

**Issue by z4ns4tsu** [System-IO-Abstractions/System.IO.Abstractions#274]
The `MockDriveInfo` type allows the caller to set various properties on instances of the class (e.g. `AvailableFreeSpace` or `DriveType`), but these properties are not included in the objects output by a call to `MockFileSystem.DriveInfo.GetDrives()` since the array is built from the list of files in the mock without checking if a `MockDriveInfo` object is defined.

*Creating the mock*
```CSharp
var fileSystem = new MockFileSystem();
fileSystem.AddFile(@"C:\path\to\file.txt", MockFileData.NullObject);
var driveInfo = new MockDriveInfo(fileSystem, "c:") { DriveType = DriveType.Fixed };
```

*Checking the drive is local*
```CSharp
List<string> localDiskDrives = 
(
    from driveInfo in fileSystem.DriveInfo.GetDrives()
    where driveInfo.DriveType == DriveType.Fixed & driveInfo.IsReady
    select driveInfo.RootDirectory.ToString()
).ToList();
```

*Expected*
List containing "c:"

*Actual*
Empty list

**Comment by sharpSteff** [comment]
I stumbled over this bug, when trying to set `AvailableFreeSpace` of the MockDriveInfo

```cs
// Set some free space
(mockFileSystem.DriveInfo.GetDrives().First() as MockDriveInfo).AvailableFreeSpace = 1024 * 1024;
var availableSpace = (mockFileSystem.DriveInfo.GetDrives().First() as MockDriveInfo).AvailableFreeSpace; 
````
After setting the `AvailableFreeSpace` and trying to get `AvailableFreeSpace` after its '0'

**Comment by fgreinacher** [comment]
Hm, I wouldn't consider this a bug, but rather a bad API. The properties at `MockDriveInfo` shouldn't be set-able. Allowing such a feature would force us to somehow maintain the used space so that we could check it against the available space on each write operation.

Other thoughts?

**Comment by ThoMAsThe** [comment]
I think it's possible if you do it through the constructor directly. Something like this would allow you to set the DriveType:

`        private class MockDriveInfo : DriveInfoBase
        {
            public MockDriveInfo(IFileSystem fileSystem, DriveType driveType) : base(fileSystem)
            {
                base.DriveType = driveType;
            }
        }`

That means you can set the DriveType as such (using Moq for FileSystem):

`var mockDriveInfo = new MockDriveInfo(_mockFileSystem.Object, DriveType.Fixed);`

**Comment by joeamnesiac** [comment]
Is there a solution or workaround for this problem?

**Comment by fgreinacher** [comment]
> Is there a solution or workaround for this problem?

I still have the same opinion as stated in https://github.com/System-IO-Abstractions/System.IO.Abstractions/issues/274#issuecomment-447978631. Does https://github.com/System-IO-Abstractions/System.IO.Abstractions/issues/274#issuecomment-563259547 help?

**Comment by mikeatdjp** [comment]
> I still have the same opinion as stated in [#274 (comment)](https://github.com/TestableIO/System.IO.Abstractions/issues/274#issuecomment-447978631). Does [#274 (comment)](https://github.com/TestableIO/System.IO.Abstractions/issues/274#issuecomment-563259547) help?

I agree with you, I don't think setting or not setting the properties is the bug.   The original poster though, described something else also, and I think that is a bug. 

" a call to MockFileSystem.DriveInfo.GetDrives() since the array is built from the list of files in the mock without checking if a MockDriveInfo object is defined."

If I define a new MockDriveInfo (fs, "/Volumes/NO NAME"), or (fs, "C:\\"), I would expect GetDrives() to return that, but it doesn't.  Is that a bug? or how can I have some control over what GetDrives() returns if I own the entire MockFileSystem?
