### ISSUE TITLE
FileInfoBase.Encrypt doesn't change attribute

### ISSUE THREAD

**Issue by Ducatel** [System-IO-Abstractions/System.IO.Abstractions#276]
Hi,

The `FileInfoBase.Encrypt` (from ` TestingHelpers.MockFileSystem` ) seem's to not set the `Encrypt` file attribut.

It can be reproduce with this code:
```
IFileSystem fileSystem = new MockFileSystem();
FileInfoBase fileInfo = fileSystem.FileInfo.FromFileName(@"c:\test.txt");
using (StreamWriter sw = fileInfo.CreateText())
{
    sw.WriteLine("plop");
}
fileInfo.Encrypt();
FileAttributes attributes = fileSystem.File.GetAttributes(fileInfo.FullName); // return System.IO.FileAttributes.Normal
Assert.AreEqual(FileAttributes.Encrypted, attributes & FileAttributes.Encrypted);
```

Version info:
```
<package id="MSTest.TestAdapter" version="1.2.0" targetFramework="net452" />
<package id="MSTest.TestFramework" version="1.2.0" targetFramework="net452" />
<package id="System.IO.Abstractions" version="2.1.0.178" targetFramework="net452" />
<package id="System.IO.Abstractions.TestingHelpers" version="2.1.0.178" targetFramework="net452" 
```

Thanks and have fun ;)

**Comment by jpreese** [comment]
Thanks for finding this @Ducatel, Resolved with #297

**Comment by Ducatel** [comment]
No problem ;)
Do you know when this fix wil be available in nuget package ?

**Comment by jpreese** [comment]
@Ducatel it is available now

**Comment by Ducatel** [comment]
Hum, I saw your last release was (v2.1.0.183) 5 days ago and the merge 2 days ...
That why, I did not check if the fix is available in current nuget package.

So I will check that ;)

**Comment by jpreese** [comment]
Strange.. the latest release should be 2.1.0.199

**Comment by Ducatel** [comment]
Last release
![image](https://user-images.githubusercontent.com/1184332/42457194-11502f9c-8397-11e8-8ca1-5fcbeac2dba8.png)

Merge
![image](https://user-images.githubusercontent.com/1184332/42457207-1f7740c4-8397-11e8-9225-fe64ac00790f.png)

**Comment by Ducatel** [comment]
So tested and working I my code ;)
Thanks for your works 😃

**Comment by jpreese** [comment]
Awesome!

2.1.0.183 is our latest release on GitHub specifically. However, our latest package on NuGet is 2.1.0.201 as of this message.

![image](https://user-images.githubusercontent.com/6980197/42509507-1be98dd0-841a-11e8-82b2-e53cf8904a41.png)
