### ISSUE TITLE
Bug introduced in 2.1.0.174 with enumerating files

### ISSUE THREAD

**Issue by TAGC** [System-IO-Abstractions/System.IO.Abstractions#277]
In a couple of unit tests for one of my projects, I create a `MockFileSystem` and `.AddDirectory("/dev/bus/usb");` I then add files under this directory such as `/dev/bus/usb/1/2`.

As part of these tests, my SUT will later execute the following method:

```cs
private void PopulateConnectedDevices()
{
    _logger.LogDebug("Populating connected USB devices under {DevDirectorPath}", _watcher.Path);
    _connectedDevices.Clear();

    foreach (var path in _fileSystem.Directory.EnumerateFiles(_watcher.Path, "*", SearchOption.AllDirectories))
    {
        var deviceFile = _fileSystem.FileInfo.FromFileName(path);

        if (!_deviceFileParser.TryParseAsDeviceInterface(deviceFile, out var vendorId, out var productId))
        {
            continue;
        }

        _logger.LogTrace("Discovered USB device (VID: {VendorId}, PID: {ProductId})", vendorId, productId);
        AddConnectedDevice(GetCanonicalPath(path), vendorId, productId);
    }
}
```

Up until System.IO.Abstractions 2.1.0.173, these unit tests passed. With System.IO.Abstractions 2.1.0.174+, it fails to enumerate any files even though they're there.

Looking at the AppVeyor build history, it seems that the bug was introduced from #258.

**Comment by TAGC** [comment]
Pinging @tathamoddie as he authored the pull request.

**Comment by MCCoolMoDAue** [comment]
I will try to reproduce the issue.

**Comment by TAGC** [comment]
I can reproduce it really easily:

```cs
[Fact]
internal void Temp()
{
    var fileSystem = new MockFileSystem();
    fileSystem.AddFile("/foo/bar.txt", "baz");
    var files = fileSystem.Directory.EnumerateFiles("/foo", "*", SearchOption.AllDirectories).ToList();
    files.ShouldHaveSingleItem();
}
```

Surprised there's apparently no unit test already in place that catches this.

**Comment by MCCoolMoDAue** [comment]
I've just created the same test, in nunit, and if you debug it, the files do contain a result!
just that nunit does not deal with it properly.
strange. I'll look into it.

**Comment by MCCoolMoDAue** [comment]
I've created the same test using NUnit, and it worked.
```csharp
[Test]
public void MockFileSystem_EnumerateFiles_ShouldReturnAllFiles()
{
	var fileSystem = new MockFileSystem();
	fileSystem.AddFile("/foo/bar.txt", "baz");

	var files = fileSystem.Directory.EnumerateFiles("/foo", "*", SearchOption.AllDirectories).ToList();

	Assert.That(files, Is.Not.Empty);
}
```
I can't reproduce the problem like that.

**Comment by TAGC** [comment]
Tried to create a Docker image to reproduce it but I forgot this library doesn't work on non-Windows platforms (#252).

[Did it with Appveyor instead.](https://ci.appveyor.com/project/TAGC/system-io-abstractions-277)
Source [here](https://github.com/TAGC/System.IO.Abstractions.277).

**Comment by MCCoolMoDAue** [comment]
Hi. Stupid mistake. My fork was still old. But on the old fork I couldn't reproduce. It's possible it was the one I introduced the PR.
Anyways, I'll look into it, but I can't build the solution.
I have to figure this out.

**Comment by MCCoolMoDAue** [comment]
Hi, I've recreated the test like this:

```csharp
        [Test]
        public void MockFileSystem_EnumerateFiles_ShouldReturnAllFiles()
        {
            var fileSystem = new MockFileSystem();
            fileSystem.AddFile(XFS.Path(@"c:\a\a\c.gif"), "content");

            var files = fileSystem.Directory.EnumerateFiles(@"C:\a", "*", SearchOption.AllDirectories).ToList();

            Assert.That(files, Is.Not.Empty);
        }
```

and it works.
The problem is that the `FixPath(´)` function will add C:\ back to your unix path.
I don't see how this is related to our work on #258.
If you do, please check out the code and point me in the right direction.

**Comment by TAGC** [comment]
Wait, what? All paths like `/foo/bar/baz` will be converted to `C:\foo/bar/baz`?

**Comment by TAGC** [comment]
In any case, I think the problem is with the changes introduced [specifically here](https://github.com/tathamoddie/System.IO.Abstractions/compare/1bf8b199...86a06ed). The `mockFileDataAccessor.Path.GetFullPath(path);` call was removed from one place and re-added further down in another method.

**Comment by MCCoolMoDAue** [comment]
I've debugged it, the issue is another one.
When you add the path to the file to the `MockFileSystem` with
` fileSystem.AddFile(XFS.Path(@"/foo/bar.txt"), "content");`
it will be converted to `c:\foo\bar.txt`
When I use windows paths it works. I deduced this means the path handling of unix paths is wrong.
But I will debug it again to check into your suggestion.

**Comment by MCCoolMoDAue** [comment]
I just added back the line you pointed out, and you are right. that fixes it.
No Tests are broken.
I'm confused however, I can make a pull request and discuss it a bit further with a maintainer.
This fix feels a bit hacky.

**Comment by jpreese** [comment]
@TAGC is this still an issue as of the latest release? I spun up a docker container running Linux with your test, and the test is passing.

![image](https://user-images.githubusercontent.com/6980197/42405617-73050032-8167-11e8-8018-908835f1eb36.png)

**Comment by TAGC** [comment]
I don't remember what project I used this for and likely won't have time at work to test this out for some time. Might be worth closing this issue, and I'll post an update if I find the issue is still present.

**Comment by jpreese** [comment]
Awesome. Thanks for the update. If it pops up again please don't hesitate to reach out.
