### ISSUE TITLE
MockFile.Delete does not throw exception when file does not exist

### ISSUE THREAD

**Issue by borismod** [System-IO-Abstractions/System.IO.Abstractions#284]
Unit test to reproduce:

```C#
var fs = new MockFileSystem();
fs.File.Delete(@"c:\someFilePath.txt");
```

The above code does not throw any exception, while the real File.Delete from System IO will throw

**Comment by jpreese** [comment]
Additional clarification.. it looks like this will break some old tests as well. We'll need to add a directory in the failing tests.

**Comment by peter-sereda** [comment]
Hello @jpreese, @fgreinacher . I have tried to fix the issue in my repository fork. Could you please check the result and tell me if something needs to be corrected?
https://github.com/peter-sereda/System.IO.Abstractions/pull/1

**Comment by fgreinacher** [comment]
Hey @peter-sereda - thanks for taking care of this. Please open a PR against this repository so that we get test results.

**Comment by peter-sereda** [comment]
@fgreinacher , done.
https://github.com/System-IO-Abstractions/System.IO.Abstractions/pull/379

**Comment by borismod** [comment]
@peter-sereda  @fgreinacher @jpreese  thanks a lot guys for your contribution. Really appreciated!
