### ISSUE TITLE
Build errors on Windows with Visual Studio 2017

### ISSUE THREAD

**Issue by robkeim** [System-IO-Abstractions/System.IO.Abstractions#306]
I've checkout out the latest master and am trying to build but receiving ~1900 build errors. Here are the first few:
```
rror	CS1703	Multiple assemblies with equivalent identity have been imported: 'C:\Users\rkeim\.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Diagnostics.Contracts.dll' and 'C:\Users\rkeim\.nuget\packages\system.diagnostics.contracts\4.3.0\ref\netstandard1.0\System.Diagnostics.Contracts.dll'. Remove one of the duplicate references.	TestHelpers.Tests(netcoreapp2.0)	C:\Users\rkeim\OneDrive\code\System.IO.Abstractions\TestHelpers.Tests\CSC	1	Active
Error	CS0433	The type 'TargetFrameworkAttribute' exists in both 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	TestHelpers.Tests(netcoreapp2.0)	C:\Users\rkeim\AppData\Local\Temp\.NETCoreApp,Version=v2.0.AssemblyAttributes.cs	4	Active
Error	CS0518	Predefined type 'System.String' is not defined or imported	TestHelpers.Tests(netcoreapp2.0)	C:\Users\rkeim\AppData\Local\Temp\.NETCoreApp,Version=v2.0.AssemblyAttributes.cs	4	Active
```

I tried looking up several solutions (reloading the solution, cleaning/restoring NuGet packages, etc), but haven't had any luck yet. Has anyone else encountered this issue or have any suggestions?

Here's a bit more detail about my setup:
- Windows 10 (v 1703)
- Visual Studio 2017 (v 15.1)

**Comment by jpreese** [comment]
@robkeim I have not seen this before and can't replicate it on either my home or work box.

Reading the first error, my gut would've been to delete the .nuget\packages folder and start a-new, but it seems you've already tried that.

I see a couple issues out there on StackOverflow where people are saying to make sure you have the latest VisualStudio and MSBuild.

**Comment by robkeim** [comment]
Thanks @jpreese I'll try upgrading the Visual Studio version. I've been hesitant to do that because last time I did it created problems in another project I had :)

**Comment by jpreese** [comment]
FWIW I'm running 15.3.3

**Comment by robkeim** [comment]
I'm happy to report that updating to Visual Studio 2017 v 15.7.4 fixed the issue 👍

**Comment by jpreese** [comment]
Awesome, good to hear!
