### ISSUE TITLE
How to find source code for specific nuget version

### ISSUE THREAD

**Issue by pasn** [System-IO-Abstractions/System.IO.Abstractions#308]
It seems that package is now automatically generated on every commit to master (or do you create nuget by hand every time)?

It would be nice if there was a git tag created for every release.

**Comment by pasn** [comment]
How to do it in yml file? Would sth like this work?

```
after_deploy:
- git tag -a v2.1.0.{build} -m "Version v2.1.0.{build}"
- git push origin v2.1.0.{build}
```

**Comment by jpreese** [comment]
We actually just had a discussion about this not too long ago in #295. As of right now, each merge into master will create a new package release, automatically. It's possible we could tag each merge, but that might be a little extreme given our current release model. 

To answer your question though, you can go to the history in AppVeyor for this project (https://ci.appveyor.com/project/tathamoddie/system-io-abstractions/history) and each time you see a full release (no hyphen at the end) the associated commit should be visible.

**Comment by pasn** [comment]
That's what I needed, thanks. :)

How can one find this link? If it is not obvious what server is being used, maybe you could add it to summary at the top of main repository's page?

**Comment by jpreese** [comment]
That is an option, yes. I'm trying to decide if having AppVeyor tag every release would be a bad thing. It's a lot of tags, but it's a lot of releases.

That way were not reliant on a 3rd party to keep our version history that may get cleaned up, and it's not very searchable.

**Comment by fgreinacher** [comment]
Independently of the tagging question, we could consider using https://github.com/dotnet/sourcelink for a much nicer debugging experience.

**Comment by fgreinacher** [comment]
Starting now all versions deployed to NuGet.org will have corresponding [tags/releases](https://github.com/System-IO-Abstractions/System.IO.Abstractions/releases).
