### ISSUE TITLE
IMockFileDataAccessor duplicates some IFileSystem members

### ISSUE THREAD

**Issue by cezarlamann** [System-IO-Abstractions/System.IO.Abstractions#309]
Hi all!

First of all, thank you for providing this awesome library!

I would like to ask you why IMockFileDataAccessor duplicates IFileSystem's methods like "File", "Directory", etc. instead of just extending IFileSystem interface?

I explain: I'm trying to use MockFileSystem together with FakeItEasy, by creating a Fake that wraps a MockFileSystem. However, when I try to configure a specific call that throws an exception (like Directory.Delete), Visual Studio tells me that the call is ambiguous between "IMockFileDataAccessor" and "IFileSystem".

So, every time I need to configure a call for "Directory", I need to cast to the interface to IFileSystem (because my objects expect an IFileSystem to work).

Is there a reason for this?

Best regards!

**Comment by rkoeninger** [comment]
Those methods/properties might be left over from an earlier version of the library. The `FileBase File { get; }` property was added to `IMockFileDataAccessor` only recently (my PR from the other day).

How necessary is `IMockFileDataAccessor`? Is there a use case for having an alternate implementation? There are no alternate implementations in the library itself that I see.

Could  we just remove that interface and have `MockFile`, `MockDirectory`, etc refer directly to their parent `MockFileSystem`?

**Comment by 304NotModified** [comment]
I think this would be nice for V6 ;)
