### ISSUE TITLE
File system should be case-sensitive on Unix

### ISSUE THREAD

**Issue by rkoeninger** [System-IO-Abstractions/System.IO.Abstractions#321]
The `MockFileSystem` uses a case-insensitive dictionary, but only on Windows is the file system case insensitive. `MockFileSystem` won't exhibit correct case-sensitivity behavior on Unix.

[Relevant line in current HEAD](https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/90eea7a4688a9c48d7cdd54641b2f407a3d9f4c9/TestingHelpers/MockFileSystem.cs#L28)

**Comment by fgreinacher** [comment]
Good catch - thanks! We have to consider back compact here though whenever someone starts working on it.

**Comment by robkeim** [comment]
@fgreinacher how do we typically handle backwards compat for "breaking" changes like this?

This looks like an easy one that I could try to pick up, I just need some guidance on handling backwards compat.

**Comment by fgreinacher** [comment]
Hm, not sure about how it was handled up to now, but what do you think about something like this:

_New types (names to be discussed):_
```csharp
public enum CasingBehavior 
{
   IgnoreCase,
   InheritFromOperatingSystem
}

// Immutable class, extensible for adding new options in the future
public sealed class MockFileSystemOptions
{
    // The default instance would have an empty current directory
    // and CasingBehavior.IgnoreCase
    public static MockFileSystemOptions Default { get; };

    public MockFileSystemOptions WithCurrentDirectory(string currentDirectory);
    public MockFileSystemOptions WithCasingBehavior(CasingBehavior casingBehavior);
}
```

_New constructor setup for `MockFileSystem`:_
```csharp

public MockFileSystem()
   : this(null, MockFileSystemOptions.Default)
{
}

public MockFileSystem(IDictionary<string, MockFileData> files)
   : this(files, MockFileSystemOptions.Default)
{
}

public MockFileSystem(IDictionary<string, MockFileData> files, string currentDirectory)
   : this(files, MockFileSystemOptions.Default.WithCurrentDirectory(currentDirectory))
{
}

// New primary constructor
public MockFileSystem(IDictionary<string, MockFileData> files, MockFileSystemOptions options)
{
}
```

_Sample usage:_ 
```csharp
var mockFileSystem = new MockFileSystem(
   files,
   MockFileSystemOptions.Default.WithCasingBehavior(CasingBehavior.InheritFromOperationSystem)
);
```

**Comment by rkoeninger** [comment]
`MockFileSystem.CurrentPlatform(files?, currentDirectory?)` would be a nice convenience. Even just in the test suite for this library.

Although, the thought did cross my mind earlier that we could have both `MockWindowsFileSystem` and `MockUnixFileSystem` as two different implementations that don't depend on `System.IO.Path` so one could test their code against both Windows and Unix behavior on the same machine. Would be a lot of work. Not suggesting as a part of this issue.

**Comment by fgreinacher** [comment]
In a world where it’s super simple to run tests in multiple environments I think it’s not necessary to invest a lot of time trying to mirror platform behaviors in a lib like this.

Regarding the convenience method: I am a big fan of immutability so I’d rather not like to have a method that changes an objects behavior drastically after it has been constructed. If you need a different file system just construct a new one.

**Comment by rkoeninger** [comment]
That was intended to be a static method. I was imagining it would pick which implementation to return, so it couldn't be a constructor.

Ignoring any out there ideas like mirroring platforms, this starts as a one-line change. The `MockFileSystem` constructor would just pick whether to use a case sensitive or insensitive comparator when it makes it's dictionary. There would be more changes necessary like [here](https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/90eea7a4688a9c48d7cdd54641b2f407a3d9f4c9/TestingHelpers/MockFileSystem.cs#L87) and I don't know where else. I guess do [a search for "OrdinalIgnoreCase"](https://github.com/System-IO-Abstractions/System.IO.Abstractions/search?q=OrdinalIgnoreCase&unscoped_q=OrdinalIgnoreCase&type=Code).

This would be more similar to current behavior where Unix/Windows behavior is not controllable and just reacts to what platform you're running on.
