### ISSUE TITLE
MockFileInfo.GetAccessControl/SetAccessControl not implemented

### ISSUE THREAD

**Issue by rkoeninger** [System-IO-Abstractions/System.IO.Abstractions#330]
Both overloads of `MockFileInfo.GetAccessControl` and the 1 method `SetAccessControl` remain unimplemented as seen [here](https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/40403faaa575206d8fe6a073ba7336b59417b922/TestingHelpers/MockFileInfo.cs#L201-L209) and [here](https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/40403faaa575206d8fe6a073ba7336b59417b922/TestingHelpers/MockFileInfo.cs#L266-L269).

Access control [is implemented for MockFile](https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/40403faaa575206d8fe6a073ba7336b59417b922/TestingHelpers/MockFile.cs#L206-L222), so this might be a fairly easy fix. 🤞

**Comment by fgreinacher** [comment]
Makes sense for File/FileInfo parity
