### ISSUE TITLE
MockFile.Create(string path, int bufferSize, FileOptions options, FileSecurity security) not implemented

### ISSUE THREAD

**Issue by rkoeninger** [System-IO-Abstractions/System.IO.Abstractions#333]
The overload of `MockFile.Create` that takes `FileSecurity` remains unimplemented as seen [here](https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/40403faaa575206d8fe6a073ba7336b59417b922/TestingHelpers/MockFile.cs#L166-L169).

**Comment by fgreinacher** [comment]
Hm, what should this do? Just set FileSecurity on the MockFile? I don’t think we want to really implement any kind of security mechanisms.

**Comment by rkoeninger** [comment]
Yeah, I think that's all it needs to do. Do whatever `MockFile.Create(string, int, FileOptions)` does and then also set the security on the `MockFileData`.

Whether or not security is enforced anywhere else is unrelated. If a security mechanism would prevent us from creating the file, that would be implemented by `Create(string)` or wherever else.

**Comment by fgreinacher** [comment]
That sounds sensible. Thanks for the reasoning!

**Comment by BKSpurgeon** [comment]
hi there

I'm made an attempt at this overload, but not sure if i'm doing it right: Would any of you have a glance over the following code and advise?

```c#
          public override Stream Create(string path, int bufferSize, FileOptions options, FileSecurity fileSecurity)
        {
            if (path == null)
            {
                throw new ArgumentNullException(nameof(path), "Path cannot be null.");
            }
            mockFileDataAccessor.PathVerifier.IsLegalAbsoluteOrRelative(path, "path");

            var directoryPath = mockPath.GetDirectoryName(path);
            if (!mockFileDataAccessor.Directory.Exists(directoryPath))
            {
                throw new DirectoryNotFoundException(string.Format(CultureInfo.InvariantCulture, StringResources.Manager.GetString("COULD_NOT_FIND_PART_OF_PATH_EXCEPTION"), path));
            }

            MockFileData mockFileData = new MockFileData(new byte[bufferSize]); // should the buffer size be added here?
            mockFileDataAccessor.AddFile(path, mockFileData);
            mockFileData.AccessControl = fileSecurity; // TODO:  should we check whether the fileSecurity object has any FileSystem access rules added to it? otherwise it might not make much sense.
            var stream = OpenWrite(path);
            return stream;
        }
```

**Comment by rkoeninger** [comment]
@BKSpurgeon if you haven't seen it already, I hashed out some code for what I thought this would look like [here](https://github.com/System-IO-Abstractions/System.IO.Abstractions/issues/331#issuecomment-406067697).

**Comment by BKSpurgeon** [comment]
Trying to get the FileOptions implemented. Is the .net code something that is looked to in implemented this: https://referencesource.microsoft.com/#mscorlib/system/io/filestream.cs,76ef6c04de9d0ed8,references

wanting some advice on how it is actually implemented. if you know pls advise.

**Comment by rkoeninger** [comment]
@BKSpurgeon I was thinking support for `FileOptions` would be done in #332. #332 should be done before this one and #331 should be done before #332. Each builds on the other. Maybe start with #331,

**Comment by BKSpurgeon** [comment]
@rkoeninger ok i'll give #331 a good shot. rgds Ben
