### ISSUE TITLE
Changes to MockFileSystem.RemoveFile causing issues with sub directories

### ISSUE THREAD

**Issue by mattdwen** [System-IO-Abstractions/System.IO.Abstractions#339]
I've just upgraded from 2.0.0.144 to find a lot of my tests breaking.

Most relate to the changes to `MockFileSystem.RemoveFile` checking if the path has the ReadOnly attribute set and throwing a UnauthorizedAccessException if so.

`MockDirectory.Move` for example enumerates all sub directories and recursively calls `Move` again. If any child file or directory of this directory have ReadOnly set then the move fails.

I can think of four possible solutions:
- Modify `MockFileSystem.RemoveFile` to check if it's a directory and not throw the exception
- Add `MockFileSystem.RemoveDirectory` and refactor to use internally
- Add a bypass to these checks. If I know I'm accessing the `MockFileSystem` from my test code, I should be able to blow away a whole directory structure without any normal file system checks.
- Manually implement an iterator in my test code to pass the filesystem checks.

I'm not 100% sure what a real file system implementation is if a subdirectory, or even a file 5 levels below is ReadOnly, but I'm pretty sure I can move the very top folder with no issues.

A lot of my code is rebuilding directory structures, so the tests are to handle scenarios where a whole directory has been deleted. It's now getting very difficult to implement this as a test.

I'm happy to create a PR, but would good to get some input first.

Cheers!

**Comment by mattdwen** [comment]
I've created a PR with a test that fails.

**Comment by ericnewton76** [comment]
First need to know what the behavior is on real filesystems like NTFS.

**Comment by mattdwen** [comment]
I've updated the PR thread with some test code to check this against a real file system, which passes on both NTFS and FAT32.

**Comment by fgreinacher** [comment]
Merged with a072541 - thanks!
