### ISSUE TITLE
NuGet package license url needs to be updated

### ISSUE THREAD

**Issue by den-mentiei** [System-IO-Abstractions/System.IO.Abstractions#341]
Currently, NuGet package has [old license URL](https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/master/License.txt) instead of [correct one](https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/master/LICENSE).

It's an issue for both `System.IO.Abstractions` and `System.IO.Abstractions.TestingHelpers` packages.

**Comment by jpreese** [comment]
Thanks for reporting this @den-mentiei! This has been resolved.
