### ISSUE TITLE
Breaking change in version 2.1.0.230

### ISSUE THREAD

**Issue by LinusNoren** [System-IO-Abstractions/System.IO.Abstractions#355]
Before version 2.1.0.230 you could do this:
`_fileSystem = new Mock<IFileSystem>();`
`_fileSystem.Setup(x => x.Directory.Exists(It.IsAny<string>())).Returns(true);`

But that doesn't work any longer, you get this error:
> Castle.DynamicProxy.InvalidProxyConstructorArgumentsException: Can not instantiate proxy of class: System.IO.Abstractions.DirectoryBase.
Could not find a parameterless constructor..

How should you write this code to get this to work now?

**Comment by fgreinacher** [comment]
@herebebeasties probably related to the changes in #352?

**Comment by fgreinacher** [comment]
Could we for this use case have an internal parameterless constructor and expose it to Moq/Castle Core via `InternalsVisibleTo`?

**Comment by herebebeasties** [comment]
Users can probably fix this by giving Moq a `DefaultValueProvider` subclass or similar (see their docs), but I agree it would be nicer if you could mock this out of the box without such apparatus.

A default internal constructor that's visible to DynamicProxyGen2 or whatever it is seems like a reasonable solution to me. Have to be a bit careful about how we signal to people who are implementing these base classes that they shouldn't be using it, though.

It might make more sense to make these things into interfaces, but that's an even bigger API break. :-/

I'll have a think and sort out a PR.

**Comment by fgreinacher** [comment]
Created a PR for the quick-fix. Long-term we should just do #175 to never again run into issues like these.

**Comment by fgreinacher** [comment]
@LinusNoren Could you verify that your problem is fixed in https://www.nuget.org/packages/System.IO.Abstractions/2.1.0.234 and give quick feedback here?

**Comment by fgreinacher** [comment]
Closing this. @LinusNoren feel free to re-open if you encounter a problem.

**Comment by LinusNoren** [comment]
Sorry @fgreinacher, I've haven't had time to verify it yet. Will try to do that tomorrow. Thanks for the fix!

**Comment by LinusNoren** [comment]
It works fine! Thank you for the help.
