### ISSUE TITLE
MockFileSystem doesn't handle FileMode.Truncate as expected

### ISSUE THREAD

**Issue by ckarras** [System-IO-Abstractions/System.IO.Abstractions#357]
Using System.IO.Abstractions.TestingHelpers 2.1.0.231

FileStream.Create with FileMode.Truncate doesn't correctly truncate existing files. If the new content written to the file is smaller than the old content, the smaller content will overwrite the begining of the file, but then the old content will remain.

Example:
```csharp
            using (var stream = fileSystem.FileStream.Create("c:\\t\\test", FileMode.Create, FileAccess.Write))
            {
                using (var writer = new StreamWriter(stream))
                {
                    writer.Write("test1234TEST5678");
                }
            }

            using (var stream = fileSystem.FileStream.Create("c:\\t\\test", FileMode.Truncate, FileAccess.Write))
            {
                using (var writer = new StreamWriter(stream))
                {
                    writer.Write("ab");
                }
            }

            fileSystem.File.ReadAllLines("c:\\t\\test").Should().Equal("ab");
```

- If `fileSystem = new FileSystem()`, then the test passes. 
- But if `fileSystem = new MockFileSystem()`, then the test fails because the file contents is: **ab**st1234TEST5678 (first 2 characters overwritten, followed by characters from the original file that shouldn't be there anymore)

**Comment by robkeim** [comment]
I made a first attempt to fix this in #358, but I'm not familiar with Truncate mode so my concern is there are other behavior differences this naive, first implementation is missing.
