### ISSUE TITLE
Release notes for 2.1.0.230

### ISSUE THREAD

**Issue by simondel** [System-IO-Abstractions/System.IO.Abstractions#363]
Dependabot just triggered a PR to update this dependency in our project. However, both Dependabot and I both can't find release notes for the 2.1.0.230 release.

**Comment by fgreinacher** [comment]
Hm, we didn’t really produce those since we switched to our „continuous release“ process. But we should really think about how to provide the necessary information to users.

**Comment by simondel** [comment]
For https://GitHub.com/stryker-mutator/stryker-net we're almost done with automating our release process and using the npm tool conventional-commits to generate a changelog based on our commit history.
