### ISSUE TITLE
System.IO.DirectoryNotFoundException after upgrade to System.IO.Abstractions.TestHelpers@2.1.0.230

### ISSUE THREAD

**Issue by simondel** [System-IO-Abstractions/System.IO.Abstractions#364]
After upgrading to System.IO.Abstractions.TestHelpers@2.1.0.230 we get the following error:
```
Starting test execution, please wait...
[xUnit.net 00:00:02.04]     Stryker.Core.UnitTest.MutationTest.MutationTestProcessTests.MutationTestProcess_MutateShouldWriteToDisk_IfCompilationIsSuccessful [FAIL]
Failed   Stryker.Core.UnitTest.MutationTest.MutationTestProcessTests.MutationTestProcess_MutateShouldWriteToDisk_IfCompilationIsSuccessful
Error Message:
 System.IO.DirectoryNotFoundException : Could not find a part of the path 'c\ExampleProject.Test\bin\Debug\netcoreapp2.0\ExampleProject.dll'.
Stack Trace:
   at System.IO.Abstractions.TestingHelpers.MockFile.Create(String path)
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate() in C:\projects\stryker-net\src\Stryker.Core\Stryker.Core\MutationTest\MutationTestProcess.cs:line 78
   at Stryker.Core.UnitTest.MutationTest.MutationTestProcessTests.MutationTestProcess_MutateShouldWriteToDisk_IfCompilationIsSuccessful() in C:\projects\stryker-net\src\Stryker.Core\Stryker.Core.UnitTest\MutationTest\MutationTestProcessTests.cs:line 207
[06:21:53 ERR] The task PrintReferences was not found in your project file. Please add the task to ExampleProject.Test.csproj
```

The mock in question is created here: https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.Core/Stryker.Core.UnitTest/MutationTest/MutationTestProcessTests.cs#L181

And is the error probably occurs here:
https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs#L78

Has something changed in the api with System.IO.Abstractions.TestHelpers@2.1.0.230?

**Comment by fgreinacher** [comment]
@rkoeninger related to #372?

We are now a bit more restrictive on what can be at the beginning of a path - the exceptions mentions a path that starts with `c\` - this is will probably be the issue here.

**Comment by simondel** [comment]
@fgreinacher @rkoeninger Thanks for the feedback! The path was indeed incorrect, but that did not fix the issue.

For now I just [create the directory](https://github.com/stryker-mutator/stryker-net/pull/136/files#diff-57ae9f21540e8d7145e9926df8ff3efbR76) before using it. During a production run, the directory already exists.

I find it to be a bit strange that a directory should exist while using a Mock, but since my issue is now resolved, I'll close this issue.

**Comment by jbaehr** [comment]
@simondel The `DirectoryNotFound` exception is by design, see #227, to mirror the behavior of System.IO.
Previously all unit tests have been green (using the Mock) but it crashed in production (not using the mock but system.io)
