### ISSUE TITLE
Should the namespace really be System.IO.Abstractions?

### ISSUE THREAD

**Issue by bentorkington** [System-IO-Abstractions/System.IO.Abstractions#365]
I get that it clearly communicates that these are abstractions for System.IO, but isn't it a bit cheeky to put the library in the System.IO namespace? That might suggest to someone unfamiliar that it is part of .NET.

**Comment by fgreinacher** [comment]
I agree this naming choice was a bit cheeky more than eight years ago, but changing that now would be a severe breaking change for all users, probably causing a lot more trouble than the confusion people might currently encounter.

Additional thoughts @jpreese @tathamoddie?

**Comment by bentorkington** [comment]
True - I agree such a breaking change would be unwelcome.

Incidentally, this was how I learned that `namespace System.IO.Abstractions { ... }` implicitly adds the System.IO namespace. In my code, I removed all my `using System.IO` lines so I didn't inadvertently leave any classes outside the abstraction layer, only to find that I needed it for constants like System.IO.FileMode, etc. anyway.

When browsing the Abstractions code, I saw the library uses these constants without fully qualified names, and without `using System.IO` anywhere.  I haven't been able to find this behaviour of the namespace keyword explicitly documented anywhere.

**Comment by jpreese** [comment]
Yeah, it's a slightly unfortunate name, but I don't think theres enough value return to go about changing it. 

We considered it when Microsoft barred the use of the System.IO namespace a bit ago, making it impossible to deploy package updates to nuget, but thats been since resolved. We were essentially grandfathered in.

**Comment by bentorkington** [comment]
Thanks for the discussion, and such a useful testing library!
