### ISSUE TITLE
Cleanup warnings for CS1591

### ISSUE THREAD

**Issue by robkeim** [System-IO-Abstractions/System.IO.Abstractions#371]
I was looking through the build output and found it was polluted by hundreds or thousands of the following warning:
`warning CS1591: Missing XML comment for publicly visible type or member`

Should we disable that warning from the build? Having cleaner build logs would help investigations when builds fail for valid reasons. The other option I see is to fix the warnings, but I don't see a good ROI on such an investment.

**Comment by fgreinacher** [comment]
Yeah, I also noticed that when working on #369, so I suppressed those warnings there. Could also split that out.

**Comment by robkeim** [comment]
Nice! Is there a reason you didn't apply the change to all of the csprojs? Does the warning on happen in the main project?

**Comment by fgreinacher** [comment]
I'm actually not sure why :) Will add to the other csprojs as well.

**Comment by fgreinacher** [comment]
This is done
