### ISSUE TITLE
Split Abstractions and Abstractions.TestingHelpers

### ISSUE THREAD

**Issue by fgreinacher** [System-IO-Abstractions/System.IO.Abstractions#381]
As discussed in #338 let's try to get this done. Here is the rough plan:

- [x] Create repo System.IO.Abstractions.TestingHelpers
- [ ] Copy necessary code to new repo
- [ ] Set up CI/CD in new repo
- [ ] Deploy TestingHelpers from new repo
- [ ] Change main repo to reference TestingHelpers via NuGet
- [ ] Delete unused code in main repo

Anything missing?

**Comment by herebebeasties** [comment]
If you want to keep the revision history rather than just copy the files, then you can do clever things with git to enable that. Let me know if you're interested and I'll drop you some commands in here to achieve that (or I can probably raise a PR that you can merge).

**Comment by fgreinacher** [comment]
That would be awesome, thanks!

**Comment by tathamoddie** [comment]
What's the benefit? Harder dev experience, more version coordination effort, for ....?

**Comment by fgreinacher** [comment]
Mostly for everything that’s mentioned in #338 - downstream projects trying to keep up with our release cadence :)

**Comment by fgreinacher** [comment]
@herebebeasties I just created [the new repo](https://github.com/System-IO-Abstractions/System.IO.Abstractions.TestingHelpers). If you want to go for some Git-fu to copy the testing helpers code there feel free to open a PR over there :)

**Comment by herebebeasties** [comment]
See System-IO-Abstractions/System.IO.Abstractions.TestingHelpers#1

**Comment by fgreinacher** [comment]
Does this still make sense now that we don't deploy directly from `master` anymore (#410)?

**Comment by fgreinacher** [comment]
Closing this as our cadence seems to be OK now. We can revisit later if necessary.
