### ISSUE TITLE
MockDirectory.GetParent() throws NullReference on Linux

### ISSUE THREAD

**Issue by peter-sereda** [System-IO-Abstractions/System.IO.Abstractions#395]
Please consider the following code:
`var fileSystem = new MockFileSystem();
 var path = XFS.Path("C:\\test.txt");
 DirectoryInfoBase dir = fileSystem.Directory.GetParent(path);`

It works ok on Windows but throws NullReferenceException on Linux. I believe this is a bug.

As a workaround, one may add an intermediate folder to the path. `fileSystem.Directory.GetParent("c:\\temp\\test.txt");` gonna work ok.

**Comment by peter-sereda** [comment]
@fgreinacher , sorry, my mistake in description. The code snippet above does not throw exception, but instead it works differently on windows and Linux. It returns a DirectoryInfoBase with "c:\\" on windows and NULL on Linux.

Standard behavior of .NET Core for `Directory.GetParent(@"c:\temp.txt");` is to return "C:\\". I believe we need to fix Linux implementation for MockDirectory to return the same. What do you think?

**Comment by fgreinacher** [comment]
@peter-sereda Sorry for not answering the question. Yes, I think we should try to mirror .NET Core behavior.

**Comment by peter-sereda** [comment]
Ok, will do.
