### ISSUE TITLE
Mock System.IO.Compression.ZipFile

### ISSUE THREAD

**Issue by samds** [System-IO-Abstractions/System.IO.Abstractions#396]
Hello guys,

For one of my project I started to write a basic wrapper around the methods of System.IO.Compression.ZipFile. To achieve that I'm of course using System.IO.Abstractions.

I started to introduce 4 new types `IZipFileFactory, ZipFileFactory, MockZipFileFactory, MockZipFileData`. Now I would like to have a property `ZipFile` of type `IZipFileFactory` in `IFileSystem` so I can write something like
```csharp
var fileSystem = new FileSystem();
fileSystem.ZipFile.CreateFromDirectory(sourceDirectoryName, destinationArchiveFileName);
...
fileSystem.ZipFile.ExtractToDirectory(destinationArchiveFileName, destinationDirectoryName);
```

Would you like to see a pull request for that feature?

Thanks

**Comment by fgreinacher** [comment]
I like the simple, extension-method based approach.

@samds Is there any major advantage in your proposal?

**Comment by samds** [comment]
@fgreinacher Well, at the time I started to write this it looked like the more natural way to do it for me. I have to give @herebebeasties' solution a try.

**Comment by ericnewton76** [comment]
Might want to consider not locking on Zip files only, and consider a more generic ICompressorStream and IVirtualFileSystem, a virtual filesystem supplied by a zip file, or vhd or similar.

I've had thoughts of doing VHD manipulation somehow using System.IO.Abstractions since VHD and ZIP files basically represent virtual filesystems with varying degrees of functionality.

Your extension methods might make an excellent candidate for a SysIOAbstractions Contrib project or SysIOVirtualFileSystems.

**Comment by fgreinacher** [comment]
Closing this. If you want to get a separate project in the SIOA org feel free to ping me here!

**Comment by EricEzaM** [comment]
@herebebeasties Any updates on open-sourcing that implementation? I am looking to make my usages of `ZipArchive` testable but am not sure how to start on the implementation you hinted at here. Would really appreciate if you could point me in the right direction to get me going.

**Comment by herebebeasties** [comment]
I've since left the company where I did this, but I can perhaps find some time to get you going if you can wait until the weekend.

**Comment by EricEzaM** [comment]
That would be good, thanks. Most basic question from would be how do you get `IFileSystem` in the `ZipArchive` extension method?

**Comment by herebebeasties** [comment]
Well it's an extension method so just something like:

```
public static class ZipExtensions
{
    public static void Unzip(this IFileSystem source, string pathToZip, IFileSystem dest, string pathToUnzipTo)
    {
        //...
    } 
} 
```

**Comment by EricEzaM** [comment]
Ah, right, thanks. I suppose I was taking your sample code below a little to literally then, with it being an ext method on ZipArchive?
```cs
public static void ExtractToDirectory(this ZipArchive zipArchive, string path);
```

**Comment by herebebeasties** [comment]
Or that, with a destination `IFileSystem` also passed in.

**Comment by gregcollingham** [comment]
Forgive me but I am trying to understand the reason for not implementing coverage of ZipFile in System.IO.Abstractions. If we are to use an extension method, doesn't that mean everyone who needs an interface on ZipFile will need to write one, where as if it was in the project in could be reused?

**Comment by vbreuss** [comment]
@greg0rym :
I created a library that abstracts the `ZipFile` methods, so that they can be abstracted via the underlying `IFileSystem` interface:
> [Testably.Abstractions.Compression](https://github.com/Testably/Testably.Abstractions)
> [![Nuget](https://img.shields.io/nuget/v/Testably.Abstractions.Compression)](https://www.nuget.org/packages/Testably.Abstractions.Compression)

In the corresponding unit tests [ZipFileTests.cs](https://github.com/Testably/Testably.Abstractions/blob/main/Tests/Testably.Abstractions.Compression.Tests/ZipFile/ZipFileTests.cs) you can see, how such tests could look...

*Even if the interfaces are not 100% compatible, you could either give my project a try or use the extension methods as a basis for implementing something similar for `System.IO.Abstractions`...*

**Comment by sakopov** [comment]
The easiest way to get around this issue is not to use `ZipFile` at all. It's a wrapper which wasn't designed to be unit tested at all. Instead, use what it wraps internally:

```csharp
using (var archiveStream = _fileSystem.FileStream.New("path/to/zip/file.zip", FileMode.CreateNew, FileAccess.Write, FileShare.None, bufferSize: 0x1000, useAsync: false))
{
    using (var archive = new ZipArchive(archiveStream, ZipArchiveMode.Create, leaveOpen: false))
    {
        var archiveEntry = archive.CreateEntry("entry.txt", CompressionLevel.Optimal);

        using (var archiveEntryStream = archiveEntry.Open())
        using (var archiveFileStream = _fileSystem.FileStream.New("path/to/entry.txt", FileMode.Open))
        {
            archiveFileStream.CopyTo(archiveEntryStream);
        }
    }
}
```

Then just use `MockFileSystem` to make your assertions.

```csharp
var fileSystemMock = new MockFileSystem();

fileSystemMock.FileExists("path/to/zip/file.zip").Should().BeTrue();
```

**Comment by cdMOE** [comment]
> public static void ExtractToDirectory(this ZipArchive zipArchive, IFileSystem destFs, string destPath);

I thought I'd comment this sample implementation in case it is helpful:

`public static void ExtractToDirectory(this ZipArchive zipArchive, IFileSystem destFs, string destPath)
    {
        ArgumentNullException.ThrowIfNull(zipArchive);
        ArgumentNullException.ThrowIfNull(destFs);
        if (string.IsNullOrEmpty(destPath)) throw new ArgumentNullException(nameof(destPath));

        foreach (var entry in zipArchive.Entries)
        {
            var entryPath = destFs.Path.Combine(destPath, entry.FullName);

            if (string.IsNullOrEmpty(entry.Name))
            {
                destFs.Directory.CreateDirectory(entryPath);
                continue;
            }

            var directoryPath = destFs.Path.GetDirectoryName(entryPath);
            destFs.Directory.CreateDirectory(directoryPath);

            using var entryStream = entry.Open();
            using var outputStream = destFs.File.Create(entryPath);
            entryStream.CopyTo(outputStream);
        }
    }`
