### ISSUE TITLE
MockDirectoryInfo.GetFiles throws DirectoryNotFoundException for UNC paths

### ISSUE THREAD

**Issue by DeveloperGuo** [System-IO-Abstractions/System.IO.Abstractions#421]
Regression introduced in v3.0.2 by #418 StringExtensions.NormalizeSlashes.

**Comment by fgreinacher** [comment]
Resolved by #422

**Comment by fgreinacher** [comment]
Thanks for reporting!

**Comment by fgreinacher** [comment]
Fixed in https://www.nuget.org/packages/System.IO.Abstractions/3.0.10
