### ISSUE TITLE
MockFileInfo.CreationTime is not correct

### ISSUE THREAD

**Issue by gplutov** [System-IO-Abstractions/System.IO.Abstractions#437]
returns "{1/2/2010 12:00:00 AM}"

**Comment by gplutov** [comment]
IFileSystem m_sut = new MockFileSystem()

string filePath = @".\testFile.txt";
m_sut.CreateFile(filePath);

IFileInfo fileInfo = m_sut.GetFileInfo(filePath);

=> fileInfo.CreationTime =  "1/2/2010 12:00:00 AM"

**Comment by fgreinacher** [comment]
Thanks - none of the timestamps is currently implemented, so I marked this as possible enhancement.
