### ISSUE TITLE
MockFileSystem.FileInfo.FromFileName("some\\directory") has Length property set to '0'

### ISSUE THREAD

**Issue by Xerillio** [System-IO-Abstractions/System.IO.Abstractions#440]
I noticed there's a discrepancy between `FileSystem` and `MockFileSystem` when returning a `FileInfoBase` for a directory path. Trying to access the `FileInfoBase.Length` property for an object returned by `FileSystem` results in a FileNotFoundException while the object from `MockFileSystem` is just 0.

It seems the `MockFileSystem` should also throw an exception to follow the .NET behaviour.

**Comment by fgreinacher** [comment]
Thanks for reporting!

**Comment by PatrykOlejniczak** [comment]
I think we can close this issue. It's fixed :)

**Comment by fgreinacher** [comment]
Yeah, will close this once we release vNext!

**Comment by fgreinacher** [comment]
This is released with https://github.com/System-IO-Abstractions/System.IO.Abstractions/releases/tag/v3.1.1
