### ISSUE TITLE
MockFileStream.Create does not fail when directory does not exists

### ISSUE THREAD

**Issue by jbaehr** [System-IO-Abstractions/System.IO.Abstractions#460]
When trying to `myFileSystem.FileStream.Create(@"someNotExistingDir\someFile")` I get a `DirectoryNotFoundException` when using a real file system (aka System.IO.FileStream), the mock file system does not reflect this behavior and silently creates the dir on the fly.

There has been a similar issue with `File.Open`, #227, that has been fixed. In System.IO.Abstractions.TestingHelpers v3.1.1 FileStream still suffers from this discrepancy between real and mock.

**Comment by fgreinacher** [comment]
Good catch, thanks for reporting. PRs welcome :)

**Comment by fgreinacher** [comment]
This is fixed with https://www.nuget.org/packages/System.IO.Abstractions/4.2.8. Thanks to @PatrykOlejniczak
