### ISSUE TITLE
Access for publication package System.IO.Abstractions.Analyzers

### ISSUE THREAD

**Issue by inyutin-maxim** [System-IO-Abstractions/System.IO.Abstractions#463]
I write code analyzers and codefixes with Roslyn for your library "System.IO.Abstractions".
I want to publish package to nuget.org, but this prefix "System.IO.Abstractions" is reserved.

Please share publication rights with my account and/or include it to organization "System-IO-Abstractions" if possible.

link to my repository: https://github.com/inyutin-maxim/System.IO.Abstractions.Analyzers

**Comment by fgreinacher** [comment]
I think using the prefix `System.` is blocked by NuGet.org by default. So moving your repository to this org will probably not change anything. @tathamoddie What did you do to get `System.IO.Abstractions` published in the first place?

**Comment by fgreinacher** [comment]
Despite that, I love the idea of your project and would happily move it to the `System-IO-Abstractions` org. You should be able to [trigger the transfer on your own](https://help.github.com/en/articles/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account)

**Comment by hangy** [comment]
> I think using the prefix `System.` is blocked by NuGet.org by default. So moving your repository to this org will probably not change anything. @tathamoddie What did you do to get `System.IO.Abstractions` published in the first place?

As far as I know, the prefix reservation is a relatively new feature on NuGet.org. The first NuGet release of `System.IO.Abstractions` seems to have been pushed in 2011 - way before the prefix reservation was implemented.

**Comment by inyutin-maxim** [comment]
@fgreinacher 
 
I tried to transfer the project to the System-IO-Abstractions organization, but received a mistake: 
"You do not have the permission to create repositories on System-IO-Abstractions"

**Comment by fgreinacher** [comment]
Sent you an invite to the org, after accepting that you should be able to transfer your repo.

Also sent out a tweet regarding the prefix: https://twitter.com/fgreinacher/status/1117504162923778048?s=21

**Comment by inyutin-maxim** [comment]
@fgreinacher I successfully transferred my project `System.IO.Abstractions.Analyzers` to the organization. Thanks for invite
