### ISSUE TITLE
MockFile.ReadAllLines does not deal with BOM correctly

### ISSUE THREAD

**Issue by fuzzykiller** [System-IO-Abstractions/System.IO.Abstractions#464]
Or, to be more precise, not at all. To deal with file data, a `StreamReader` must be used. This is also what .NET internally does.

Consider the following example:

```
var fs = new MockFileSystem();
fs.AddDirectory("U:\\");
fs.File.WriteAllLines("U:\\Test.txt", new[] { "Hallo Welt"}, Encoding.UTF8);
var chars = fs.File.ReadAllLines("U:\\Test.txt", Encoding.UTF8).Single().ToArray();
```

`chars[0]` is now `65279`, which is the BOM. That’s because the encoding is used directly:

https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/452e3312776c14843806b14224ba82ae5d5ec137/System.IO.Abstractions.TestingHelpers/MockFile.cs#L496-L498

I’ll create a pull request later, if that’s okay.

---

Also, while I’m at it, might I ask why this library even bothers with trying to deal with text as a special case? This introduces unnecessary complexity and potential for differences in behavior with actual System.IO.

**Comment by 304NotModified** [comment]
@fgreinacher could you please answer these questions?

> I’ll create a pull request later, if that’s okay.

> Also, while I’m at it, might I ask why this library even bothers with trying to deal with text as a special case? This introduces unnecessary complexity and potential for differences in behavior with actual System.IO.

**Comment by fgreinacher** [comment]
> @fgreinacher could you please answer these questions?
> 
> > I’ll create a pull request later, if that’s okay.

Sure, that would be fine.

> 
> > Also, while I’m at it, might I ask why this library even bothers with trying to deal with text as a special case? This introduces unnecessary complexity and potential for differences in behavior with actual System.IO.

TBH, I have no idea. Maybe @tathamoddie remembers?

**Comment by 304NotModified** [comment]
> Also, while I’m at it, might I ask why this library even bothers with trying to deal with text as a special case? This introduces unnecessary complexity and potential for differences in behavior with actual System.IO.

I think drop

Maybe include this also for V6?

**Comment by fuzzykiller** [comment]
Sorry for the long delay. Upon further investigation I found that the default encoding in `MockFileContent` does not match the .NET default. This leads to further inconsistencies between this library and the real filesystem. I will not fix this fundamental flaw, it’s too much of a change.

I have a unit test for the reported issue here: 

https://github.com/fuzzykiller/System.IO.Abstractions/commit/b525129938cafd6af9cef4059b2ba5d46936c04c

**Comment by siprbaum** [comment]
I see that this is marked as stale, but it looks like a real problem. 
Due to the the lack of a concrete solution, could this at least be documented as a known issue, e.g. in the release notes or the README?

**Comment by fgreinacher** [comment]
No worries, issues that get comments won’t be closed, that’s what this workflow is for 😊
