### ISSUE TITLE
MockFileSystem construction throws ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by dzarda** [System-IO-Abstractions/System.IO.Abstractions#466]
Using version 4.1.6 from NuGet, Windows, xUnit

- In an xUnit test I have a MockFileSystem field
- In the test constructor I have a `MockFileSystem(IDictionary, string)` constructor call
- This constructor throws:
  - System.ArgumentOutOfRangeException : **Index was out of range**. Must be non-negative and less than the size of the collection.
  - Parameter name: **startIndex**
  - Stack trace:  
    - at System.String.**IndexOf**(String value, Int32 **startIndex**, Int32 count, StringComparison comparisonType)
    - at System.IO.Abstractions.TestingHelpers.**MockFileSystem.AddDirectory**(String path
    - at System.IO.Abstractions.TestingHelpers.**MockFileSystem..ctor**(IDictionary`2 files, String currentDirectory)

Relevant lines:

```cs
            _darkFile = Path.Combine("baseDir", "subDir", "darkFile");
            _brightFile = Path.Combine("baseDir", "subDir", "brightFile");
            _defectFile = Path.Combine("baseDir", "subDir", "defectFile");
            _correction = new Mock<ICorrection>();
            _fs = new MockFileSystem(
                new Dictionary<string, MockFileData>
                {
                    { _darkFile, new MockFileData(string.Empty) },
                    { _brightFile, new MockFileData(string.Empty) },
                    { _defectFile, new MockFileData(string.Empty) },
                }, "."); // When I use the default `""`, no exception is thrown
```

**Comment by fgreinacher** [comment]
Although this clearly is a regression: What is the purpose of setting the working directory to `.`?

**Comment by dzarda** [comment]
This is an older piece of code where I tried forcing MockFS to treat the paths as absolute.

**Comment by fgreinacher** [comment]
> This is an older piece of code where I tried forcing MockFS to treat the paths as absolute.

Thank you! As you say "I tried" I assume it didn't really work out well 😅  

I consider using any kind of relative paths for this constructor parameter as invalid (relative to what should it be?) and would propose to just provide a better exception.

**Comment by dzarda** [comment]
Well, I don't want anything prepended in front of those paths. If I don't pass that workdir argument, it's taking the working directory of the REAL file system and prepending it.

I've been digging through the exact same topic some time ago here: #350

**Comment by fgreinacher** [comment]
Well, actually it now defaults to the root directory (`C:` on Windows, `/` on Unix):

https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/761c6e3d0acde7e36334369773f8822700a35c7d/System.IO.Abstractions.TestingHelpers/MockFileSystem.cs#L23
