### ISSUE TITLE
Potential MemLeak because IFileSystemWatcher does not implement IDisposable

### ISSUE THREAD

**Issue by BADF00D** [System-IO-Abstractions/System.IO.Abstractions#469]
Hi,
I just stumble upon the fact, that IFileSystemWatcher is not IDisposable, but all its Implementation are. When I retrieve an instance from IFileSystemWatcherFactory, I have no hint that I have to dispose this instance. Which can lead to memory leaks. Given that FileSystemWatcher is a system resource, it might also be there after my program finished.

For me there are two solution to this problem:

1. Make IFileSystemWatcher IDisposable (my preferred solution).
2. Add a Release method to IFileSystemWatcherFactory, that handles the dispose call for me.

**Comment by fgreinacher** [comment]
Thanks for reporting! I’d also prefer the first solution.
