### ISSUE TITLE
Looking for a abstraction layer for both local filesystem and cloud filesystem like Azure Bolbs

### ISSUE THREAD

**Issue by iron9light** [System-IO-Abstractions/System.IO.Abstractions#473]
Hi,
I'm looking at a common IO/FileSystem abstraction layer for both local/remote/cloud.
For the cloud, I mean Azure Storage Blobs, etc.
To support those scenarios, I think your lib should add async ops support.
What do you think?

**Comment by robkeim** [comment]
@iron9light are you referring to the group of methods with names ending in Async? If so, I think this issue has been brought up as an enhancement in #441.

**Comment by iron9light** [comment]
For most cases, yes, they are the same issue.
But I just wondering if it's possible that we add even more async methods like list all child for a directory, etc. Since in the cloud scenario, everything should be async by default.
