### ISSUE TITLE
MockFileSystem.Directory.GetFiles bug with relative path

### ISSUE THREAD

**Issue by sa-he** [System-IO-Abstractions/System.IO.Abstractions#475]
I hope the following code is self explaining:

```C#
[Fact]
public void RelativePathBugTest()
{
    // arrange
    var fileSystem = new MockFileSystem(new Dictionary<string, MockFileData>());
    const string dir = @"C:\test";
    fileSystem.Directory.SetCurrentDirectory(dir);
    fileSystem.AddFile($@"C:\test.txt", new MockFileData("Some ASCII text."));

    fileSystem.File.Exists(@"C:\test.txt").Should().BeTrue();
    fileSystem.File.Exists(@"..\test.txt").Should().BeTrue(); // relative path works fine

    fileSystem.Directory.GetFiles(@"C:\").Length.Should().Be(1);
    fileSystem.Directory.GetFiles(@"..\").Length.Should().Be(1); // this line fails. 
}
```

**Comment by fgreinacher** [comment]
Thanks for reporting! For additional context can you please answer...
1. whether this works with the real `FileSystem` and
2. how your call fails (assertion failure or crash?) 

Thanks!

**Comment by sa-he** [comment]
1. it is only with the MockFileSystem
2. System.IO.DirectoryNotFoundException: Could not find a part of the path '..'.
   bei System.IO.Abstractions.TestingHelpers.MockDirectory.GetFilesInternal(IEnumerable`1 files, String path, String searchPattern, SearchOption searchOption)
   bei System.IO.Abstractions.TestingHelpers.MockDirectory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   bei System.IO.Abstractions.TestingHelpers.MockDirectory.GetFiles(String path, String searchPattern)
   bei System.IO.Abstractions.TestingHelpers.MockDirectory.GetFiles(String path)
   bei ClassLibrary1.Class1.RelativePathBugTest() in

**Comment by vigneshmoha** [comment]
@sa-he @fgreinacher I have a raised the following PR to fix this issue.. Please let me know your comments.

**https://github.com/System-IO-Abstractions/System.IO.Abstractions/pull/505**

**Comment by vigneshmoha** [comment]
@sa-he This is now fixed and merged. Can you close it if you are happy?

**Comment by fgreinacher** [comment]
Fixes with https://www.nuget.org/packages/System.IO.Abstractions/6.0.32
