### ISSUE TITLE
Could I test System.Security.Permissions?

### ISSUE THREAD

**Issue by 304NotModified** [System-IO-Abstractions/System.IO.Abstractions#480]
Hi,

Could I test System.Security.Permissions, like the FileIOPermission with awesome abstraction / library?

**Comment by fgreinacher** [comment]
Currently not. If you like to have this feature feel free to create a new issue describing the use cases, a rough sketch of necessary API changes in `System.IO.Abstractions` and an outline of how mocking those APIs would look like. Thanks!
