### ISSUE TITLE
Proposal: add coverage (cloud) to the CI

### ISSUE THREAD

**Issue by 304NotModified** [System-IO-Abstractions/System.IO.Abstractions#483]
Hi,

Thanks for this library :)

It would be nice if the unit test coverage is measured. You could do that in combination with AppVeyor.

There are at least two options:

- Use opencover with codecov.io (free) - only coverage, see for example https://github.com/NLog/NLog.web and https://codecov.io/github/NLog/NLog.Web?branch=master
- Or use opencover with SonarQube (also free) - coverage + code smells etc. But could take some more built time. See for example: https://github.com/NLog/NLog.extensions.logging and https://sonarcloud.io/component_measures?id=nlog.extensions.logging&metric=coverage

With both options I could help if needed.

**Comment by fgreinacher** [comment]
Good idea! I added the codecov app to this project. Happy to take a PR for this. The encrypted codecov token is ycLGfgCWit9AZy3mh2U5vfcz7Nl8Y/WJjTrp4q/d15vjMl2X4rapPVAkW5ZuMqdk

**Comment by 304NotModified** [comment]
OK I will try to get things working in my fork and then I will send a PR

**Comment by 304NotModified** [comment]
Working on this, but it's hard because the assembly starts with System. 

After many times I found out that there is a default filter (with System*). Now it's working, but it's fast on my machine < 20 seconden, but on appveyor it takes 15-20 minutes :O

**Comment by 304NotModified** [comment]
Could you please try how long this takes on your machine?

```
nuget.exe install OpenCover -ExcludeVersion -DependencyVersion Ignore

OpenCover\tools\OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test -f netcoreapp2.0 -c debug System.IO.Abstractions.TestingHelpers.Tests"  -nodefaultfilters  -filter:"-[System]* -[System.IO]* +[System.IO.Abstractions]* +[System.IO.Abstractions.TestingHelpers]* -[System.IO.Abstractions.TestingHelpers.Tests]*" -output:"coverage.xml" -oldstyle

```

**Comment by fgreinacher** [comment]
Sorry, I only have a Mac at hand. I made some good experience with [Coverlet](https://github.com/tonerdo/coverlet), it works cross-platform and I think it can also output OpenCovers XML format.
