### ISSUE TITLE
Cannot catch exception thrown by File.WriteAllBytesAsync

### ISSUE THREAD

**Issue by JerrettDavis** [System-IO-Abstractions/System.IO.Abstractions#491]
When attempting to use `IFile.WriteAllBytesAsync`, all underlying exceptions from `File.WriteAllBytesAsync` are quietly disregarded. I can see the exceptions being thrown, but a `try/catch` fails to catch the exceptions. Instead, the program continues execution on the next line. I believe this is due to the `FileWrapper` not awaiting the response from `File.WriteAllBytes`, and instead it's always returning a Task.Completed task.

**Comment by robkeim** [comment]
@JerrettDavis in order to catch exceptions thrown by async methods you need to await their results like this:
```
Task<Result> resultTask = someMethodThatReturnsAResultByThrowsAnException();
// No exception is thrown at this point
// Continue doing other work...
try
{
    Result result = await resultTask; // this will now throw an exception
}
catch (Exception e)
{
    // Handle your exception here
}
```

Here you can see a quick fiddle that I threw together showing this behavior:
https://dotnetfiddle.net/7jj6lJ

**Comment by JerrettDavis** [comment]
@robkeim Ordinarily, that would work, but it doesn't appear to work properly for `WriteAllBytesAsync`.

Here is an example method:

```csharp
public async Task<string> SaveFileAsync(string path, byte[] file, string fileType, CancellationToken cancellationToken = default)
{
    var filename = _filenameProvider.GetFilename(path, fileType);
    var fullPath = _fileSystem.Path.Combine(path, filename)?.Replace('/', '\\');

    _fileSystem.Directory.CreateDirectory(path);
    try
    {
        await _fileSystem.File.WriteAllBytesAsync(fullPath, file, cancellationToken);
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex);
    }

    return filename;
}
```

The `catch` block is never triggered, but

**Comment by fgreinacher** [comment]
This is fixed with https://github.com/System-IO-Abstractions/System.IO.Abstractions/releases/tag/v6.0.15, should be on NuGet.org soon

**Comment by JerrettDavis** [comment]
It's live on nuget, and the fix is confirmed working in my original use-case.
