### ISSUE TITLE
How to add empty directory to MockFileSystem?

### ISSUE THREAD

**Issue by Loreno10** [System-IO-Abstractions/System.IO.Abstractions#495]
Question is as in the topic. I tried like this:
```csharp
            _mockFileSystem = new MockFileSystem(new Dictionary<string, MockFileData>
            {
                { _rootDirWithoutFiles, null }
            });
```

It throws exception that null is not acceptable.

**Comment by robkeim** [comment]
I don't think there's an option to create empty directories using a constructor directory. You have to use the `AddDirectory` method:
```
_mockFileSystem = new MockFileSystem();
_mockFileSystem.AddDirectory(_rootDirWithoutFiles);
```

**Comment by Loreno10** [comment]
Fine, I now see that I can use IFileSystem's Directory to create directories.
