### ISSUE TITLE
Support File.ReadAllLinesAsync and friends on .NET Core 3 / netstandard2.1

### ISSUE THREAD

**Issue by christianrondeau** [System-IO-Abstractions/System.IO.Abstractions#499]
Async methods were implemented in https://github.com/System-IO-Abstractions/System.IO.Abstractions/pull/481#issuecomment-521274716 but I think the precompiler directives or somehow the nuget binding doesn't get them.

Sample csproj:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Abstractions" Version="6.0.21" />
  </ItemGroup>
</Project>
```

Sample code:

```
var lines = await new FileSystem().File.ReadAllLinesAsync(@"C:\file.txt")
```

I think the problem is simply that we're limited to NETCOREAPP2_0: https://github.com/fedoranimus/System.IO.Abstractions/blob/master/System.IO.Abstractions/FileBase.cs#L322 - you can probably instead use `NETSTANDARD2_0` but I won't be able to test that right away. I won't be able to provide a PR as I'm off until the end of next week, but if no one took this issue when I'm back all provide one.

**Comment by fgreinacher** [comment]
Your sample csproj is targeting .NET Standard 2.1 and will therefore pull in the .NET Standard 2.0 version of System.IO.Abstractions.

Back in #481 we added support for the async overloads to a newly added .NET Core 2.0 target. To solve your issue we need to add an additional target for .NET Standard 2.1 in which we could light up the async overloads.
