### ISSUE TITLE
Test for auto label #2

### ISSUE THREAD

**Issue by fgreinacher** [System-IO-Abstractions/System.IO.Abstractions#513]
The `MockDriveInfo` type allows the caller to set various properties on instances of the class (e.g. `AvailableFreeSpace` or `DriveType`), but these properties are not included in the objects output by a call to `MockFileSystem.DriveInfo.GetDrives()` since the array is built from the list of files in the mock without checking if a `MockDriveInfo` object is defined.

*Creating the mock*
```CSharp
var fileSystem = new MockFileSystem();
fileSystem.AddFile(@"C:\path\to\file.txt", MockFileData.NullObject);
var driveInfo = new MockDriveInfo(fileSystem, "c:") { DriveType = DriveType.Fixed };
```

*Checking the drive is local*
```CSharp
List<string> localDiskDrives = 
(
    from driveInfo in fileSystem.DriveInfo.GetDrives()
    where driveInfo.DriveType == DriveType.Fixed & driveInfo.IsReady
    select driveInfo.RootDirectory.ToString()
).ToList();
```

*Expected*
List containing "c:"

*Actual*
Empty list

**Comment by joeamnesiac** [comment]
Why is this closed? Is there a workaround/fix?

**Comment by fgreinacher** [comment]
This is just a copy of #274 to test an auto labeling app 😀
