### ISSUE TITLE
Bug: Filesystem serialization & deserialization works with fileSystem.GetFile(path).Contents) but not fileSystem.File.ReadAllBytes(path));

### ISSUE THREAD

**Issue by darl2ng** [System-IO-Abstractions/System.IO.Abstractions#520]
For now directories and files are restored but reading file content raises null exception:

```csharp
// save:
IFormatter formatter = new BinaryFormatter();
            Stream stream = new FileStream(Path.GetTempPath() + "test.io", FileMode.Create, FileAccess.Write);
            formatter.Serialize(stream, fileSystem);
            stream.Close();

// reload
IFormatter formatter = new BinaryFormatter();
            Stream stream = new FileStream(Path.GetTempPath() + FS_FILENAME, FileMode.Open, FileAccess.Read);
            IFileSystem fileSystem = (MockFileSystem)formatter.Deserialize(stream);
            stream.Close();
            return fileSystem;

// read
fileSystem.File.ReadAllBytes(fileInfo.FullName); // => exception
```

**Comment by fgreinacher** [comment]
Thanks for the report! Would be more actionable if you'd include the callstack for the exception.

**Comment by darl2ng** [comment]
namespace System.IO.Abstractions.TestingHelpers.Tests
{
    using NUnit.Framework;
    using System.Reflection;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using Text;
    using XFS = MockUnixSupport;
    [TestFixture]
    class MockFileSystemSerializationTests
    {

        const string FS_FILENAME = @"test.fs";

        [Test]
        public void SerializationTexts()
        {
            // Arrange
            string path = XFS.Path(@"c:\something\demo.txt");

            var content = "Hello there!" + Environment.NewLine + "Second line!" + Environment.NewLine;

            var fileSystem = new MockFileSystem();
            fileSystem.AddDirectory(XFS.Path(@"c:\something"));

            fileSystem.File.WriteAllText(path, content);

            //Act
            SaveFileSystem(fileSystem);
            fileSystem = (MockFileSystem) LoadFileSystem();

            //Clear
            ClearFileSystem();

            // Assert
            Assert.AreEqual(
                content,
                fileSystem.GetFile(path).Contents);
            Assert.AreEqual(
                content,
                fileSystem.File.ReadAllText(path));

        }
        [Test]
        public void SerializationBytes()
        {
            // Arrange
            string path = XFS.Path(@"c:\something\demo.txt");

            var content = "Hello there!" + Environment.NewLine + "Second line!" + Environment.NewLine;
            var expected = Encoding.ASCII.GetBytes(content); //Convert a C# string to a byte array

            var fileSystem = new MockFileSystem();
            fileSystem.AddDirectory(XFS.Path(@"c:\something"));

            fileSystem.File.WriteAllBytes(path, expected);

            //Act
            SaveFileSystem(fileSystem);
            fileSystem = (MockFileSystem)LoadFileSystem();

            //Clear
            ClearFileSystem();

            // Assert
            Assert.AreEqual(
                expected,
                fileSystem.GetFile(path).Contents);
            Assert.AreEqual(
                content,
                fileSystem.File.ReadAllBytes(path));
        }
        private void SaveFileSystem(MockFileSystem fileSystem)
        {
            IFormatter formatter = new BinaryFormatter();
            Stream stream = new FileStream(Path.GetTempPath() + FS_FILENAME, FileMode.Create, FileAccess.Write);
            formatter.Serialize(stream, fileSystem);
            stream.Close();
        }
        private IFileSystem LoadFileSystem()
        {
            IFormatter formatter = new BinaryFormatter();
            Stream stream = new FileStream(Path.GetTempPath() + FS_FILENAME, FileMode.Open, FileAccess.Read);
            IFileSystem fileSystem = (MockFileSystem)formatter.Deserialize(stream);
            stream.Close();
            return fileSystem;
        }
        private void ClearFileSystem()
        {
            string temp = Path.GetTempPath() + FS_FILENAME;
            if (File.Exists(temp))
                File.Delete(temp);
        }
    }
}

**Comment by darl2ng** [comment]
> Thanks for the report! Would be more actionable if you'd include the callstack for the exception.

You're welcome. I've put a test unit that you can use to reproduce the bug, which shows:            fileSystem.GetFile(path).Contents works ok but not fileSystem.File.ReadAllBytes(path));

Best,

**Comment by darl2ng** [comment]
My investigation leads to MockFileSystem's PathVerifier pathVerifier is not serializable so it's empty when deserialize and raise exception. A quick fix would be marking PathVerifier as serializable and remove UnSerialized PathVerifier pathVerifier in MockFileSystem.
