### ISSUE TITLE
Mock GetFiles/GetFileSystemEntries does not list files

### ISSUE THREAD

**Issue by Xerillio** [System-IO-Abstractions/System.IO.Abstractions#525]
I've noticed that using `Directory.GetFiles` and `Directory.GetFileSystemEntries` does not return files in the given directory. See below example, where a real `FileSystem` works as expected but the `MockFileSystem` does not

```C#
[Test]
public void TestSneakyFile()
{
    var realFs = new FileSystem();
    realFs.Directory.CreateDirectory("C:/a");
    realFs.Directory.CreateDirectory("C:/a/b");
    realFs.File.WriteAllText("C:/a/testfile.txt", "some content");

    // All assertions succeed
    Assert.That(realFs.Directory.GetFileSystemEntries("C:/a"), Has.Length.EqualTo(2));
    Assert.That(realFs.Directory.GetFiles("C:/a"), Has.Length.EqualTo(1));
    Assert.That(realFs.Directory.GetDirectories("C:/a"), Has.Length.EqualTo(1));
    Assert.That(realFs.File.ReadAllText("C:/a/testfile.txt"), Is.EqualTo("some content"));

    realFs.Directory.Delete("C:/a", true);


    var fs = new MockFileSystem(new Dictionary<string, MockFileData>
    {
        { "C:/a/testfile.txt", new MockFileData("some content") },
        { "C:/a/b", new MockDirectoryData() },
    });

    // These assertions fail: Length is 1 lower than expected
    Assert.That(fs.Directory.GetFileSystemEntries("C:/a"), Has.Length.EqualTo(2));
    Assert.That(fs.Directory.GetFiles("C:/a"), Has.Length.EqualTo(1));

    // These assertions succeed
    Assert.That(fs.Directory.GetDirectories("C:/a"), Has.Length.EqualTo(1));
    Assert.That(fs.File.ReadAllText("C:/a/testfile.txt"), Is.EqualTo("some content"));
}
```

**Version (from NuGet):** 2.1.0.236
**OS:** Testing from Windows 10

**Comment by fgreinacher** [comment]
Thanks for reporting! Which OS are you on? the usage of forward slashes seems that you’re testing this on Unix, while the `c:` at the start indicates Windows.

**Comment by Xerillio** [comment]
I'm testing from a Windows 10 pc - I put it in the original post too now.
The forward slashes is mostly for readability since it's compatible with both Unix and Win

**Comment by fgreinacher** [comment]
Yep, we assume „correct“ path separators. I assume your test cases would work if you build paths with `.Path.Combine`.

**Comment by siprbaum** [comment]
But if it works with System.IO but not with the Mocks it is clearly a problem with the mocks. 
The product code can't control ftom where it gets its paths, because they might be directly frtom user input

**Comment by Xerillio** [comment]
@fgreinacher you are correct. The assertions do pass if I replace all `/` with `\\`.
However, I agree with @siprbaum that since System.IO handles it without issues I would expect the mocks to do the same.

**Comment by fgreinacher** [comment]
Got it, thanks! I’ll mark it as up for grabs, so feel free to get started on it if you want 😁

**Comment by Xerillio** [comment]
After having a little look at the source I was wondering why I was experiencing this issue and realized I should have just updated my project to use the latest version of this library.

This bug is not present in the latest code and works after updating my project, so apologies for the bug report :) I'll close it.

**Comment by fgreinacher** [comment]
No worries and thanks for the update!

**Comment by baibhavgh550** [comment]
Getting almost the same issue here. Cannot get files in the mock system. 
filesSystem.Directory.Exists(@"C:\csv\") returns true
fileSystem.DirectoryInfo.FromDirectoryName(@"c:\csv\").GetFiles() returns no files

fileSystem.FileInfo.FromFileName(@"c:\csv\test.txt")  returns does not exist

So basically I can find directories but when I do GetFiles its empty( tried using Path.Combine but that did not work- well the directory path is fine so that could not be the issue)
Tried updating to the latest nuget but still the same thing

https://stackoverflow.com/questions/61123112/system-io-abstractions-mockfilesystem-getfiles-not-returning-any-files

**Comment by fgreinacher** [comment]
@baibhavgh550 Which version are you using?
