### ISSUE TITLE
How to read file from windows network share?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [System-IO-Abstractions/System.IO.Abstractions#527]
Right now I can't make it "network" because whatever network path I inform (smb://mySharedServer/sharedFolder or \\\\mySharedServer/sharedFolder) gets prepended with /Users/Me/Projects/MySolutionPath

**Comment by fgreinacher** [comment]
UNC paths in Windows need to start with `\\`, which should work with our wrappers if you are on Windows. Can share a snippet that works with `System.IO` and does not work with this library?

**Comment by Leonardo-Ferreira** [comment]
yes, the thing is that either with "\\" or "smb://" it doesn't work... but take into consideration that the server actually running the code will not be windows! The server providing the network share is, but the server consuming it is not!

**Comment by fgreinacher** [comment]
OK, understood, thanks for clarifying. Can you share a snippet that works with standard `System.IO` APIs, but fails with our wrappers?

**Comment by Leonardo-Ferreira** [comment]
Actually I managed to figure it out to be an issue with the Core Fx... so far the workaround is to call `mount_smbfs` and mount a local volume and then access this "local" folder

**Comment by fgreinacher** [comment]
Thank you! Is there anything we can improve here? I assume the workaround with the local paths also works with SIOA.

**Comment by fgreinacher** [comment]
Closing this, feel free to reopen if anything should change here.
