### ISSUE TITLE
FileStream.Create with FileMode.CreateNew doesn't throw exception when file already exists

### ISSUE THREAD

**Issue by PaulVrugt** [System-IO-Abstractions/System.IO.Abstractions#532]
When not using mocking, creating a filestream using FileMode.CreateNew throws an IOException when the target file already exists. However, the MockFileStream constructor behaves differently. When passing CreateNew as FileMode, it truncates the file. This causes issues for us in our unit tests, since the test scenario behaves differently than then real code.

**Comment by fgreinacher** [comment]
Thanks for reporting!
