### ISSUE TITLE
Update IDirectory interface to net standard 2.1

### ISSUE THREAD

**Issue by sszakal** [System-IO-Abstractions/System.IO.Abstractions#537]
In net standard 2.1, three new overloads have been added for file and directory search. (better performance and also allows you to skip inaccessible files/directories) 

```
IEnumerable<string> EnumerateDirectories(string path, string searchPattern, EnumerationOptions enumerationOptions);

IEnumerable<string> EnumerateFiles(string path, string searchPattern, EnumerationOptions enumerationOptions);

IEnumerable<string> EnumerateFileSystemEntries(string path, string searchPattern, EnumerationOptions enumerationOptions);
```

There's already a pull request open for this Interface update. In order to call these new methods from the unit test project I also had to add net core 2.1 as a target, and because some methods (access control) have removed in 2.1, I had to add few more preprocessor directives to exclude them for that build.

https://github.com/System-IO-Abstractions/System.IO.Abstractions/pull/536

**Comment by fgreinacher** [comment]
Done what #536
