### ISSUE TITLE
CreateDirectory doesn't throw exception when the path contains illegal characters

### ISSUE THREAD

**Issue by ArnaudB88** [System-IO-Abstractions/System.IO.Abstractions#546]
When not using mocking, creating a directory with an illegal character (eg. '?') throws an exception.
With mocking, it simply succeeds.

Used method:
MockFileSystem.Directory.CreateDirectory("c:\\temp\\Invalid_?_");

**Comment by fgreinacher** [comment]
Thanks for reporting!
