### ISSUE TITLE
Could not load file or assembly 'System.Security.AccessControl', Version=4.1.1.0

### ISSUE THREAD

**Issue by angellaa** [System-IO-Abstractions/System.IO.Abstractions#547]
**I am unable to use any type in System.IO.Abstractions (version 8.0.3) in a test project targeting .NET Framework 4.7.2** 

1. Download and extract the following project for a minimal reproduction:

[FileSystemTest.zip](https://github.com/System-IO-Abstractions/System.IO.Abstractions/files/4097397/FileSystemTest.zip)

2. Build the project using `dotnet build`
3. Run the tests in the project `dotnet test FileSystemTest\bin\Debug\net472\FileSystemTest.dll`

I expect the test to pass, instead we get a FileLoadException.

```
**>dotnet test FileSystemTest\bin\Debug\net472\FileSystemTest.dll**

Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
  X CanCreateFileSystem [207ms]
  Error Message:
   **System.IO.FileLoadException : Could not load file or assembly 'System.Security.AccessControl, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)**
  Stack Trace:
     at System.IO.Abstractions.FileSystem..ctor()
   at FileSystemTest.Program.CanCreateFileSystem() in c:\FileSystemTest\FileSystemTest\Program.cs:line 12

Test Run Failed.
Total tests: 1
     Failed: 1
 Total time: 1.4191 Seconds
```

Note: the test pass when using the old csproj format of if we change the project to be a console application.

From the assembly metadata of `System.IO.Abstractions` looks like is referencing `System.Security.AccessControl` version 4.1.1.0. However, the version of `System.Security.AccessControl` copied in build output is version 4.1.3.0. The latter is what the nuget package claim to depend on.

![image](https://user-images.githubusercontent.com/641111/72896793-69b1f080-3d18-11ea-9566-29d6cd9c0399.png)

**Comment by fgreinacher** [comment]
Thanks for reporting, I’ll try to have a look this week!

**Comment by jflepp** [comment]
In version `7.1.10` one could simply exchange the `System.IO.Abstractions.dll` with the net40 compilation to work on the .NET Framework (Required when authoring libraries compiled on netstandard but consumed by a netframework app).

A resolution to this issue could be to simply re-add the .NET Framework target, which is anyway the recommended way to provide multi targeted libraries.

```
CONSIDER adding a target for net461 when you're offering a netstandard2.0 target.
```
from: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting#multi-targeting

**Comment by fgreinacher** [comment]
We actually have a very similiar setup in our tests: https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/master/System.IO.Abstractions.TestingHelpers.Tests/System.IO.Abstractions.TestingHelpers.Tests.csproj. Why do you invoke `dotnet test` on the output assembly? Adding a package reference to `Microsoft.NET.Test.Sdk` in your sample and running the test case via a plain `dotnet test` works for me.

**Comment by fgreinacher** [comment]
> In version `7.1.10` one could simply exchange the `System.IO.Abstractions.dll` with the net40 compilation to work on the .NET Framework (Required when authoring libraries compiled on netstandard but consumed by a netframework app).
> 
> A resolution to this issue could be to simply re-add the .NET Framework target, which is anyway the recommended way to provide multi targeted libraries.
> 
> ```
> CONSIDER adding a target for net461 when you're offering a netstandard2.0 target.
> ```
> 
> from: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting#multi-targeting

Right below they say:

> Using .NET Standard 2.0 from .NET Framework has some issues that were addressed in .NET Framework 4.7.2. You can improve the experience for developers that are still on .NET Framework 4.6.1 - 4.7.1 by offering them a binary that is built for .NET Framework 4.6.1.

So everything should be fine with .NET Framework 4.7.2.

**Comment by jflepp** [comment]
These issues were addressed, but not completely resolved. That's also why a `System.Security.AccessControl` support package is required when using System.IO.Abstractions in netstandard2.0 with net472, while there is no support package required with the .NET Framework targeted System.IO.Abstractions compilation.

+ In order to use the package with net472, some assembly redirections to the support DLLs would be required. This is probably the problem @angellaa is facing, as the executing application is the `dotnet` command.

+ As the .NET Framework 4.7.1 will be supported for quite a few years, there will surely be consumers of your package using net46-net471 for years to come.

I'm not sure if all of my statements are 100% correct, please correct me if some are wrong. But as of now, I cannot see a way to use your package in a .NET 472 plugin scenario.

**Comment by jflepp** [comment]
I did a small check using the net48:

It is not possible to consume the System.IO.Abstractions package in version 8.0.4 without specifying the `AutoGenerateBindingRedirects` flag to true, which writes following app.config:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" />
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Security.AccessControl" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.3.0" newVersion="4.1.3.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

So the support package `System.Security.AccessControl` really is required when consuming the `System.IO.Abstractions` in the .NET Framework.

**Comment by fgreinacher** [comment]
Yes, it is required and transitively referenced this reference:

https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/dbf2548f14eed656be81f9bbafafeaa4241c5c12/System.IO.Abstractions/System.IO.Abstractions.csproj#L13

Binding redirects are usually created automatically by the .NET SDK (or the .NET Test SDK for test projects). 

I don't see a "normal" usage pattern that does not work. If you have something I can try please put it in a Gist/repo. Thanks!

**Comment by mark-raymond** [comment]
There are several situations where binding redirects are not possible, such as PowerShell cmdlets and SSMS/VS plugins.

**Comment by jflepp** [comment]
Basically whenever you do not have access to the `app.config` of the executing application.
I do think this is a valid and quite common usage pattern.

**Comment by fgreinacher** [comment]
Hm, I think a lot of libraries depend on binding redirects, so unless there is a solution that does not involve adding back a netfx target I think we have to live with that behavior.

**Comment by ThomasBarnekow** [comment]
I just ran into the issue with version 8.0.5 in a WiX bundle project that uses an extension I built. The latter depends on System.IO.Abstractions 8.0.5, which transitively depends on the System.Security.AccessControl NuGet package in version 4.7.0 with a DLL version 4.1.3.0. However, the System.IO.Abstractions.dll references System.Security.AccessControl.dll version 4.1.1.0, which does not match the DLL version 4.1.3.0 of the NuGet package.

WiX installer projects seemingly do not support binding redirects, so I was out of luck. Thus, I had to downgrade again to a version of my extension that depends on System.IO.Abstractions version 7.1.10.

The above-mentioned version mismatches look like a bug in your NuGet packages.

**Comment by fgreinacher** [comment]
Thanks for all your scenarios. So the common problem seems to be that this specific dependency “upgrade” cannot be handled by .NET Framework without explicit binding redirects. 

TBH, I have no idea how I as a maintainer can help here without providing a dedicated .NET framework target (what I’d rather not do going forward).

Maybe some experts can provide additional hints? Maybe @davidfowl, @terrajobst or @onovotny?

**Comment by ThomasBarnekow** [comment]
@fgreinacher Could you elaborate on why you don't want to provide a dedicated .NET Framework target?

I've just played around with the `System.IO.Abstractions.csproj` file, adding `net461` as a target:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>System.IO.Abstractions</AssemblyName>
    <RootNamespace>System.IO.Abstractions</RootNamespace>
    <Description>A set of abstractions to help make file system interactions testable.</Description>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net461</TargetFrameworks>
    <PackageProjectUrl>https://github.com/System-IO-Abstractions/System.IO.Abstractions</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>testing</PackageTags>
    <DefineConstants Condition="'$(TargetFramework)' == 'netstandard2.1'">$(DefineConstants);FEATURE_ASYNC_FILE;FEATURE_ENUMERATION_OPTIONS</DefineConstants>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' or '$(TargetFramework)' == 'netstandard2.1' ">
    <PackageReference Include="System.IO.FileSystem.AccessControl" Version="4.7.0"/>
  </ItemGroup>
</Project>
```

For `net461` (and later), you don't need to reference `System.IO.FileSystem.AccessControl`, i.e., the assembly that causes the failure. Therefore, providing a .NET Framework target such as `net461` (or later) would likely solve the issue. At least on my local machine, all unit tests passed (noting that the `net461` target was tested using the `net472` target you specified in your unit test project).

I saw that version 7.1.10 targeted `net40` rather than `net461` and I do understand that this might have caused issues that you now want to avoid (and I have seen other projects abandon anything up to `ne452` as those versions are no longer supported by Microsoft). While I don't know which issues you faced exactly, I'd think that targeting a reasonably recent .NET Framework (no older than net461`, which I replaced with `net472` at the end of last year in my projects) should not create issues.

**Comment by fgreinacher** [comment]
I just want to keep this library as straightforward as possible, following MS advice over at https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting. Looking at some comments at the docs pages I’m not sure anymore what’s the right way to go there. I’m somehow leaning towards adding a net461 target, as that should be API compatible with netstandard20.

**Comment by ThomasBarnekow** [comment]
I support your view on keeping the library straightforward. I would appreciate a decision to add a `net461` target,

**Comment by fgreinacher** [comment]
Thanks for all your thoughts - I just added a net461 target (#554). New version (8.1.x) will be on NuGet.org soon.

**Comment by ThomasBarnekow** [comment]
@fgreinacher Thanks a lot. This has solved my issue!

**Comment by oscarcauich** [comment]
would this package work if my project is targeting .Net 4.7.2?

**Comment by fgreinacher** [comment]
> would this package work if my project is targeting .Net 4.7.2?

Yes!
