### ISSUE TITLE
Add Support for Path.IsPathFullyQualified

### ISSUE THREAD

**Issue by HaGGi13** [System-IO-Abstractions/System.IO.Abstractions#548]
Please add support for [`Path.IsPathFullyQualified(string)`](https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Private.CoreLib/src/System/IO/Path.cs#L267-L293) wich was added with .NET Core 2.1 and is part of .NET Standard 2.1.

_Further information:_
Microsoft inervts the result of an internal method named `IsPartiallyQualified(string)`. You could find it's implementation [here](https://github.com/dotnet/runtime/blob/e59c9260eb78bbf093d8081a3b8a1ecc0132d70f/src/libraries/Common/src/System/IO/PathInternal.Windows.cs#L150-L186).
This method uses two more methods named [`IsDirectorySeparator(char)`](https://github.com/dotnet/runtime/blob/e59c9260eb78bbf093d8081a3b8a1ecc0132d70f/src/libraries/Common/src/System/IO/PathInternal.Windows.cs#L188-L195) and [`IsValidDriveChar(char)`](https://github.com/dotnet/runtime/blob/e59c9260eb78bbf093d8081a3b8a1ecc0132d70f/src/libraries/Common/src/System/IO/PathInternal.Windows.cs#L54-L60).

**Comment by fgreinacher** [comment]
Good suggestion! Let’s do it together with #399 👍
