### ISSUE TITLE
Strongly-typed overloads

### ISSUE THREAD

**Issue by flcdrg** [System-IO-Abstractions/System.IO.Abstractions#560]
System.IO.Abstractions as it is currently implemented wraps the existing System.IO classes and methods.

I was thinking whether there would be any value in providing overloads for methods that have `IDirectoryInfo`, `IFileInfo`, etc as parameters instead of strings?

eg. 

```
IPath.Combine(IDirectoryInfo path1, IDirectoryInfo path2);
IPath.Combine(IDirectoryInfo path1, IFileInfo path2);
```

Or if there would be a way of providing this as an optional layer somehow?

**Comment by fgreinacher** [comment]
One key thing about this library is that it can be used (mostly) as drop-in replacement for System.IO. Changing APIs is therefore nothing we should do IMO. If you want "better" APIs it's probably better to use/build a dedicated thing.

Other opinions?

**Comment by fgreinacher** [comment]
No other opinions, so I am closing this. Feel free to provide convenience methods like these in a separate NuGet package! 👍
