### ISSUE TITLE
MockFileSystem should throw IOException when process cannot access file, because it is being used by another process.

### ISSUE THREAD

**Issue by ttlaare** [System-IO-Abstractions/System.IO.Abstractions#561]
![image](https://user-images.githubusercontent.com/47394927/75393448-677e1b80-58ee-11ea-8623-ad22c5f92562.png)

MockFileSystem should throw an IO exception when a process cannot access the file in a MockFileSystem when it's being used in another process. I would like to test that a method throws this exception when the input file is being used in another process.

**Comment by hangy** [comment]
Should this be an option that's set when the `MockFileSystem` is created? I suppose the behaviour of `FileSystem` greatly differs based on the actual file system and operating system: What causes and Exception on Windows with NTFS is no problem at all on *NIX with an FS like ext4.

**Comment by ttlaare** [comment]
I think adding an option when the MockFileSystem is created is a great solution.

**Comment by fgreinacher** [comment]
Have you seen `MockFileData.AllowedFileShare`?

https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/f21bf9f87ea32d9ad28239035230ef9bc2beb13e/System.IO.Abstractions.TestingHelpers/MockFileData.cs#L168

It was introduced for use cases like this one. You can also have a look at the related tests:

https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/f21bf9f87ea32d9ad28239035230ef9bc2beb13e/System.IO.Abstractions.TestingHelpers.Tests/MockFileLockTests.cs

**Comment by ttlaare** [comment]
@fgreinacher, I've missed 'MockFileData.AllowedFileShare'. It works now. Thanks!
![image](https://user-images.githubusercontent.com/47394927/75667313-be317f80-5c77-11ea-9c72-fcce88719fe2.png)

**Comment by ttlaare** [comment]
@fgreinacher No, I've missed MockFileData.AllowedFileShare. With this I can test if the method throws an IOException when it's being used in another process. Thanks a lot!
