### ISSUE TITLE
Lack of Path.TrimEndingDirectorySeparator on .NET Core 3.1

### ISSUE THREAD

**Issue by Stuv7CB** [System-IO-Abstractions/System.IO.Abstractions#562]
Lack of Path.TrimEndingDirectorySeparator on .NET Core 3.1

https://docs.microsoft.com/en-us/dotnet/api/system.io.path.trimendingdirectoryseparator?view=netcore-3.1

**Comment by fgreinacher** [comment]
We don't target .NET Core for maintainability reasons. Feel free to add this via an extension method on `IPath`.
