### ISSUE TITLE
Mocking symlink

### ISSUE THREAD

**Issue by garyng** [System-IO-Abstractions/System.IO.Abstractions#575]
Is it possible for mocking symlink for unit testing?

**Comment by fgreinacher** [comment]
Currently not. Could you sketch out the desired API shape?

**Comment by garyng** [comment]
This was in the back of my head for some time now... Kinda difficult unless `System.IO` itself handles symlink right?

**Comment by fgreinacher** [comment]
Yeah, that's why I was asking :) I don't think there is anything in `System.IO` that is specific to symlinks, IMO they are handled transparently by the OS. What's the test you want to write?

**Comment by garyng** [comment]
You are right. I wonder why I asked this question in the first place...

I think this probably can be closed, unless something for manipulating symlinks are provided in `System.IO`.

**Comment by fgreinacher** [comment]
Alright - no worries 👍
