### ISSUE TITLE
Add overloads to the CreateNew method of IFileSystemWatcherFactory

### ISSUE THREAD

**Issue by nathanpovo** [System-IO-Abstractions/System.IO.Abstractions#577]
The [`FileSystemWatcher`](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher.-ctor?view=netframework-4.8) constructor in `System.IO` has 3 overloads:

```csharp
FileSystemWatcher()
FileSystemWatcher(string path)
FileSystemWatcher(string path, string filter)
```

The `IFileSystemWatcherFactory` is missing the constructor which includes the filter.

Also, is there a reason why the 2 methods of `IFileSystemWatcherFactory` are implemented as separate methods instead of using an overload?

I can create a pull request to fix the issue.

**Comment by fgreinacher** [comment]
> The IFileSystemWatcherFactory is missing the constructor which includes the filter.

Correct, seems like nobody needed it up to now 🤣 

> Also, is there a reason why the 2 methods of IFileSystemWatcherFactory are implemented as separate methods instead of using an overload?

I have no idea, that's really weird. I'd vote to obsolete `FromName` and go all in with `CreateNew` overloads.

> I can create a pull request to fix the issue.

Awesome, go for it 🚀
