### ISSUE TITLE
Adding filter list on FileSystemWatcher

### ISSUE THREAD

**Issue by RenatoChitolina** [System-IO-Abstractions/System.IO.Abstractions#583]
Hello!

Since Core 3.x, we have a filter list on the FileSystemWatcher, to provide an easy way to handle multiple file types.

```csharp
var watcher = new FileSystemWatcher();
watcher.Filters.Add("*inbound*.xlsx");
watcher.Filters.Add("*inbound*.csv");
```
Would be possible to consider adding it to next versions?

**Comment by fgreinacher** [comment]
Thanks for the hint! We currently don't target .NET Core. As .NET Standard and .NET Core will converge into .NET 5 soon-ish I'd like to add this when we build the first .NET 5 package 👍

**Comment by fgreinacher** [comment]
Blocked by #633
