### ISSUE TITLE
IDirectoryInfo missing .NET Standard 2.1 overloads

### ISSUE THREAD

**Issue by sherman89** [System-IO-Abstractions/System.IO.Abstractions#593]
First of all thank you for this wonderful library!

I noticed while refactoring my code that the following overload was missing from IDirectoryInfo EnumerateFiles:
**EnumerateFiles(String, String, EnumerationOptions)**

So in order to make use of EnumerationOptions, I had to change my code to use the Directory property from IFileSystem instead. Not a huge deal since there is a workaround, but would be nice to also have these.

Cheers

**Comment by fgreinacher** [comment]
Thanks for the hint! Sounds like a great first PR 👍

**Comment by sherman89** [comment]
@fgreinacher 

Sorry for the late reply, lots of work. 

That sounds fine, I'll try to do it as soon as I have the time :-)

Cheers

**Comment by IrisClasson** [comment]
Saw that the issue had gone stale, happy to help if you don't have the time @sherman89

**Comment by sherman89** [comment]
@fgreinacher 
I finally found the time to do this. Here's a link to the PR:
https://github.com/System-IO-Abstractions/System.IO.Abstractions/pull/641

@IrisClasson 
A quick review and testing would be appreciated 👍 Thanks for the help!

**Comment by fgreinacher** [comment]
Fixed by #641
