### ISSUE TITLE
File.Move and File.MoveTo with overwrite option

### ISSUE THREAD

**Issue by mwagenfuehr** [System-IO-Abstractions/System.IO.Abstractions#595]
**Describe the solution you'd like**
Starting with .NET Core 3.1 (not sure if in 3.0 aswell) Microsoft introduced the following overloads:
- `System.IO.File.Move(string, string, bool)` [see here](https://docs.microsoft.com/de-de/dotnet/api/system.io.file.move?view=netcore-3.1#System_IO_File_Move_System_String_System_String_System_Boolean_)
- `System.IO.FileInfo.MoveTo(string, bool)` [see here](https://docs.microsoft.com/de-de/dotnet/api/system.io.fileinfo.moveto?view=netcore-3.1#System_IO_FileInfo_MoveTo_System_String_System_Boolean_)

where the user could say if he wants to overwrite the destination (if there's already a file).

I noticed that this NuGet-Package only supports net461, netstandard2.0 and netstandard2.1. These features are only available in netcoreapp3.1 though. Is there any chance you guys will consider supporting stuff like this too? Would be helpful i guess (also considering the future of .NET Core and stuff)

**Comment by mwagenfuehr** [comment]
Related to #582

**Comment by fgreinacher** [comment]
Thanks for your suggestion! This is very similar to #583. As mentioned in https://github.com/System-IO-Abstractions/System.IO.Abstractions/issues/583#issuecomment-619586881 I prefer to stay with .NET Standard (and .NET Framework for compat) and add new functionality once .NET 5 is out.

**Comment by mwagenfuehr** [comment]
Totally understand that decision! Thanks for the head-up. I'm looking forward to the implementation of this feature.

**Comment by fgreinacher** [comment]
Blocked by #633
