### ISSUE TITLE
Inconsistent behavior with real filesystem: new MockFileSystem().FileStream.Create("ONLY_FILE_NAME.txt")

### ISSUE THREAD

**Issue by LatteAno** [System-IO-Abstractions/System.IO.Abstractions#600]
The following fails:

    using (new MockFileSystem().FileStream.Create("ONLY_FILE_NAME.txt", FileMode.Create)) { }
    // System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'FILE_NAME.txt'.'

While its equivalent in real file-system, succeeds:

    using (new FileStream("ONLY_FILE_NAME.txt", FileMode.Create)) { }

**Comment by fgreinacher** [comment]
Thanks for your report!
