### ISSUE TITLE
Consider making IServiceCollection extension method

### ISSUE THREAD

**Issue by GeeWee** [System-IO-Abstractions/System.IO.Abstractions#604]
**Is your feature request related to a problem? Please describe.**
When using the built in ASP.NET core dependency injection, I often have to write code like this:
```csharp
services.AddTransient<IFileSystem, FileSystem>();
services.AddTransient<IDirectory, DirectoryWrapper>();
services.AddTransient<IFileInfoFactory>((provider) => provider.GetService<IFileSystem>().FileInfo);
```

**Describe the solution you'd like**
It would be nice if `System.IO.Abstractions` defined an extension method on `IServiceCollection` like `AddPhysicalFileSystem` which made sure to register all the necessary dependencies in the DI container.

**Comment by fgreinacher** [comment]
This would require us to introduce a new dependency https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.Abstractions which is not supported on .NET Framework (which we are targeting here). Also ASP.NET Core has it's [own file system abstractions](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/file-providers?view=aspnetcore-3.1) which I think should be prefered to "raw" I/O.

I'm therefore closing this, but anyway thanks a lot for your suggestion!

**Comment by GeeWee** [comment]
Perfectly fair. Thanks for considering it!

**Comment by govorovvs** [comment]
Let's create conditional package reference
```
<ItemGroup Condition="'$(TargetFramework)' != 'net461'">
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
```
