### ISSUE TITLE
[Question] Read-Only Permission

### ISSUE THREAD

**Issue by t-knapp** [System-IO-Abstractions/System.IO.Abstractions#605]
Hello,

does the lib support permissions on files and directories?

I'd like to set an directory to read-only. Is it possible?

Kind regards,
Tobias

**Comment by fgreinacher** [comment]
API-wise yes:

```csharp
            var readOnlyDirectory = new MockDirectoryData();
            readOnlyDirectory.Attributes |= FileAttributes.ReadOnly;
            var fileSystem = new MockFileSystem(new Dictionary<string, MockFileData>
            {
                { XFS.Path(@"c:\readonly"), readOnlyDirectory }
            });
```

But I don't think we currently check readonly-ness of directories anywhere. Sounds like a good - though not trivial - contribution 👍

**Comment by fgreinacher** [comment]
Closing this issue as the question in answered. Please write follow-up issues in case you encounter problems or are missing an API?
