### ISSUE TITLE
Creating a filestream with FileAccess.Write returns true for CanRead using testinghelpers

### ISSUE THREAD

**Issue by PaulVrugt** [System-IO-Abstractions/System.IO.Abstractions#610]
**Describe the bug**
When creating a filestream using FileAccess.Write:

`_fileSystem.FileStream.Create(filePath, FileMode.CreateNew, System.IO.FileAccess.Write);`

during unit testing, the property `CanRead` for this stream returns `true`, when it should be `false`

**To Reproduce**
use mockfilesystem, and create a file stream using:
`_fileSystem.FileStream.Create(filePath, FileMode.CreateNew, System.IO.FileAccess.Write);`

**Expected behavior**
`CanRead` property of the created stream returns `false`

**Comment by fgreinacher** [comment]
Thanks for reporting!
