### ISSUE TITLE
Path.Join is missing on IPath interface

### ISSUE THREAD

**Issue by GeeWee** [System-IO-Abstractions/System.IO.Abstractions#623]
`Path.Join` is not implemented on the `IPath` interface. While there's Path.Combine which does (almost) the same thing, it'd be wonderful to have `Join` as well, so IPath becomes more of a drop-in replacement.

**Comment by fgreinacher** [comment]
Thanks for the issue 👍. 

Needs to be limited to the [.NET Standard 2.1 API](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.join?view=netstandard-2.1) and we should probably also add [`IPath.TryJoin`](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.tryjoin?view=netstandard-2.1) while we're at it.

**Comment by GeeWee** [comment]
Woohoo!
