### ISSUE TITLE
System.IO.Abstractions.TestingHelpers latest version is 12.0.5 and not 12.0.8

### ISSUE THREAD

**Issue by Mobrockers** [System-IO-Abstractions/System.IO.Abstractions#626]
**Describe the bug**
It seems something went wrong with releaseing the TestingHelpers package again, the latest three versions are missing on nuget.org

**Comment by fgreinacher** [comment]
Looking good to me: https://www.nuget.org/packages/System.IO.Abstractions/12.0.8 🤔 Maybe you just picked a bad time?

**Comment by Mobrockers** [comment]
> Looking good to me: https://www.nuget.org/packages/System.IO.Abstractions/12.0.8 🤔 Maybe you just picked a bad time?

That's the main package, https://www.nuget.org/packages/System.IO.Abstractions.TestingHelpers/ is the one that's not up to date.

**Comment by fgreinacher** [comment]
Oops 😬 Thanks, I’ll have a look today!

**Comment by fgreinacher** [comment]
Seems like we are hitting https://github.com/NuGet/Home/issues/4393 here :( Fix in progress.

**Comment by fgreinacher** [comment]
Fixed starting with https://www.nuget.org/packages/System.IO.Abstractions.TestingHelpers/12.0.9. Thanks again for reporting this issue!
