### ISSUE TITLE
Different Behaviour for Directory.GetParent(..) with root folder as argument

### ISSUE THREAD

**Issue by IloSophiep** [System-IO-Abstractions/System.IO.Abstractions#635]
**Describe the bug**
There seems to be a difference between the call to `System.IO.Abstractions.Directory.GetParent(..)` and the normal `System.IO.Directory.GetParent(..)`. Because i think that this package tries to mirror the "to be expected" return values and exceptions i opened up this issue.

**To Reproduce**
We are using the version v12.1.1 of System.IO.Abstractions in our project.

We had a loop to find a specific subfolder starting from an executable file name going up to root.
E.g. if the file is **C:\foo\bar\myapp.exe** we wanted to find **C:\foo\\.peter**. The important part of that loop is our call to
`currentPath = Directory.GetParent(currentPath)`. Afterwards we would check `currentPath == null` to see if we "stepped out of root", so to say.

For example `Directory.GetParent("C:\\") == null`, so our loop would stop there.

Now with `_filesystem.Directory.GetParent("C:\\")` we get an `ArgumentNullException`, even though we never had to handle this exception before.

**Expected behavior**
I think the behaviour of the two methods should be the same?

**Additional context**
If it was a special decission to differ the behaviour then this whole bug can be closed pretty quickly. I did not find any info (quickly) that made me sure it was intended or not, so i figured i would just report it like this. 

After taking a quick look, the problem seems to be 
https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/a786e3bf4f10f5842925a6d2d7a6eb22edbc15b1/src/System.IO.Abstractions/DirectoryWrapper.cs#L139
where the `null`-Result from the original `Directory.GetParent(..)` just gets passed into the `DirectoryInfoWrapper`-ctor - which throws on `null` arguments:
https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/a786e3bf4f10f5842925a6d2d7a6eb22edbc15b1/src/System.IO.Abstractions/DirectoryInfoWrapper.cs#L14

I want to finish with thanking you a lot for this package! It made it real simple to test some heavy file accessing in our projects and made us be able to cover our logic with unittests way quicker! Thank you.

**Comment by fgreinacher** [comment]
Thanks for the detailed description @IloSophiep! Yes, this is indeed a bug. The `null` result from `Directory.GetParent` should  be propagated to the caller. I'm marking this a `ready` so feel free to send a PR 👍

**Comment by IloSophiep** [comment]
Sorry for only getting back to you now..!

Can you give me some hints what i would need to provide in a PR to have this merged?

I would simply check the result of `Directory.GetParent(path)` and return it if `null` or return the wrapped result.

Am i correct in thinking i should also add a new test (similar to https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/a786e3bf4f10f5842925a6d2d7a6eb22edbc15b1/tests/System.IO.Abstractions.Tests/DirectoryInfoTests.cs#L9) in a new test file (like `DirectoryWrapperTests.cs`) that checks the result of the call `_filesystem.Directory.GetParent("C:\\")` to be `null`?

Sorry again for the late response and thanks already for the help.

**Comment by fgreinacher** [comment]
> Sorry for only getting back to you now..!

No worries, I also took some days off 😄 

> Can you give me some hints what i would need to provide in a PR to have this merged?
> 
> I would simply check the result of `Directory.GetParent(path)` and return it if `null` or return the wrapped result.
> 
> Am i correct in thinking i should also add a new test (similar to
> 
> https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/a786e3bf4f10f5842925a6d2d7a6eb22edbc15b1/tests/System.IO.Abstractions.Tests/DirectoryInfoTests.cs#L9
> 
> ) in a new test file (like `DirectoryWrapperTests.cs`) that checks the result of the call `_filesystem.Directory.GetParent("C:\\")` to be `null`?

Yes, that sounds perfect!
