### ISSUE TITLE
[Question] Mock FileStream as a parameter

### ISSUE THREAD

**Issue by hasan-hasanov** [System-IO-Abstractions/System.IO.Abstractions#636]
Hello I have searched on the internet but could not find an answer. Is it possible to create a FileStream and pass it to a method using System-IO-Abstractions?

I have the following method:

```
public void Copy(FileStream file, pathTo)
{
    // Some file processing...

    _fileSystem.File.Copy(file.Name, pathTo);

    // Some more processing...
}
```

I want to create a FileStream using MockFileSystem and pass it inside the method.
I do not want to change the method signature.

I am using netstandard2.0

Is it possible to test this method?

**Comment by fgreinacher** [comment]
Unfortunately that's not possible because `FileStream` needs to be backed by a file existing on disk (which is not that case when using `MockFileSystem`.
