### ISSUE TITLE
What's the proper syntax when working with `FileStream`?

### ISSUE THREAD

**Issue by pdevito3** [System-IO-Abstractions/System.IO.Abstractions#637]
**Description of bug and reproducing it**
Hey guys, I've got the method below that I am trying to abstract out for testing. File and Directory additions are working fine, but when working with the filestream on `using (FileStream fs = fileSystem.File.Create(classPath.FullClassPath))`, I am getting an `Cannot implicitly convert type 'System.IO.Stream' to 'System.IO.FileStream'. An explicit conversion exists (are you missing a cast?)` error. I'm assuming I should use something else for the `FileStream` type, but I'm not seeing it in the docs, issues, etc.

```csharp
        public static void CreateEntity(string solutionDirectory, Entity entity, IFileSystem fileSystem)
        {
            try
            {
                var classPath = ClassPathHelper.EntityClassPath(solutionDirectory, $"{entity.Name}.cs");

                if (!fileSystem.Directory.Exists(classPath.ClassDirectory))
                    fileSystem.Directory.CreateDirectory(classPath.ClassDirectory);

                if (fileSystem.File.Exists(classPath.FullClassPath))
                    throw new FileAlreadyExistsException(classPath.FullClassPath);

                using (FileStream fs = fileSystem.File.Create(classPath.FullClassPath))
                {
                    var data = GetEntityFileText(classPath.ClassNamespace, entity);
                    fs.Write(Encoding.UTF8.GetBytes(data));
                }

                GlobalSingleton.AddCreatedFile(classPath.FullClassPath.Replace($"{solutionDirectory}{Path.DirectorySeparatorChar}", ""));
            }
            catch (FileAlreadyExistsException e)
            {
                WriteError(e.Message);
                throw;
            }
            catch (Exception e)
            {
                WriteError($"An unhandled exception occurred when running the API command.\nThe error details are: \n{e.Message}");
                throw;
            }
        }
```

**Expected behavior**
I'd expect to be able to do something along the lines of `fileSystem.FileStream` like I've done with `File` or `Directory`, but no luck. Assuming there's just a simple syntax difference I'm missing.

**Comment by pdevito3** [comment]
🤦‍♂️ Literally just thought of the solution after I posted it. Sorry guys.

For others that run into this, I just updated it to var and it was completely fine:
```csharp
                using (var fs = fileSystem.File.Create(classPath.FullClassPath))
                {
                    var data = GetEntityFileText(classPath.ClassNamespace, entity);
                    fs.Write(Encoding.UTF8.GetBytes(data));
                }
```

**Comment by siprbaum** [comment]
I was curious on what was going on. Just for reference, here are my findings:
`System.IO.File.Create` returns a FileStream, whereas using System.IO.Abstractons `IFileSystem.File.Create` returns a `Stream` to allow easier mocking.
