### ISSUE TITLE
12.1.9 All *Async methods missing in netstandard2.0

### ISSUE THREAD

**Issue by DaanWasscher** [System-IO-Abstractions/System.IO.Abstractions#642]
In an earlier version the *Async methods were available in the netstandard2.0 target. Now they are only present in the netstandard2.1 target of s.io.a. 

I have a project with TargetFramework "netcoreapp2.1" for which I would like to use the *async methods.

I have been looking through the releases and commits but can't find a definitive answer if that is a bug or intended behavior.

**Comment by fgreinacher** [comment]
https://github.com/System-IO-Abstractions/System.IO.Abstractions/pull/540 removed the .NET Core targets from this library. If you need newer features, you have to upgrade your project to at least .NET Core 3 or stay with SIOA <= 7.1.10.

Sorry for the hassle but this is a one-man-show and I need to keep maintenance effort low.
