### ISSUE TITLE
Path.Join methods don't honor Path1

### ISSUE THREAD

**Issue by LinearCore** [System-IO-Abstractions/System.IO.Abstractions#643]
When using the FileSystem object. The PathWrapper object methods, according to source, for the Path.Join methods use 

```cs
public override string Join(ReadOnlySpan<char> path1, ReadOnlySpan<char> path2) =>
            Path.Join(path2, path2);
```

instead of:

```cs
 public override string Join(ReadOnlySpan<char> path1, ReadOnlySpan<char> path2) =>
            Path.Join(path1, path2);
```

**To Reproduce**
1. Go to 'https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/main/src/System.IO.Abstractions/PathWrapper.cs'

2. Scroll down to 'Line 135'

**Expected behavior**

```cs
 public override string Join(ReadOnlySpan<char> path1, ReadOnlySpan<char> path2) =>
            Path.Join(path1, path2);
```

Change the methods to use Path1, instead of Path2

**Comment by fgreinacher** [comment]
🤦 Thanks for reporting!

**Comment by LinearCore** [comment]
No problem, love the project.
