### ISSUE TITLE
CancellationToken doesn't work when unit testing

### ISSUE THREAD

**Issue by adamradocz** [System-IO-Abstractions/System.IO.Abstractions#647]
**Describe the bug**
When unit testing and a `CancellationToken` is passed to abort a function with `ReadAllBytesAsync` or `WriteAllBytesAsync`, the function runs normally.

**To Reproduce**
1. Create a function with `ReadAllBytesAsync` or `WriteAllBytesAsync`.
2. Create a unit test in xUnit and pass a canceled token to test the function. (`var cancellationToken = new CancellationToken(true);`) 

**Expected behavior**
When a canceled token is passed in the unit test, abort the `ReadAllBytesAsync` and `WriteAllBytesAsync` functions.

**Comment by fgreinacher** [comment]
Very good finding. Thank you!
