### ISSUE TITLE
Override DirectorySeparatorChar / AltDirectorySeparatorChar

### ISSUE THREAD

**Issue by vchirikov** [System-IO-Abstractions/System.IO.Abstractions#648]
Sometimes I need to test a code that uses `Path.DirectorySeparatorChar` from `MockFileSystem`. But today it's can't be mocked, because `Path` is not overridable.

**Describe the solution you'd like**
virtual getter or something like this:
```cs
public class MockPath // ...
{
  public char DirectorySeparatorChar {get; set;}  = Path.DirectorySeparatorChar;
}

**Comment by fgreinacher** [comment]
Thanks, for the issue. I don't fully understand what you're asking for as the property `MockPath.DirectorySeparatorChar` is already virtual:

https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/352f6002196b7f3428df7192eaae6520fbcff6f7/src/System.IO.Abstractions/PathWrapper.cs#L15-L18

**Comment by vchirikov** [comment]
```cs
        [Fact]
        public void Test()
        {
            MockFileSystem fs = new MockFileSystem(new Dictionary<string, MockFileData>{
                {"C:\\file.txt", MockFileData.NullObject}
            });
            // now for example I want to change PathSeparator, but Path only have getter and I have to use another approach for testing
            // (for example vitual method for accessing Path.DirectorySeparator) or reflection.
            var mockPath = (MockPath)fs.Path;
            // can't do this
            // mockPath.PathSeparator = '\\'; 
            var moqPath = new Mock<MockPath>(fs, MockUnixSupport.Path("C:\\temp"));
            moqPath.Setup(m => m.DirectorySeparatorChar).Returns('#');
            var fi = fs.GetType().GetField($"<Path>k__BackingField", BindingFlags.Instance | BindingFlags.NonPublic);
            fi.SetValue(fs, moqPath.Object);
            Assert.Equal('#', fs.Path.DirectorySeparatorChar);
            moqPath.Verify(m => m.DirectorySeparatorChar, Times.Once);
        }
```
This is what I'm talking about.

**Comment by fgreinacher** [comment]
This can solved without reflection or any other hacks. You just to make sure that the `Mock` is working on the interfaces, not on the `Mock*` classes:

```csharp
        [Test]
        public void Test()
        {
            var fsMock = new Mock<MockFileSystem>(new Dictionary<string, MockFileData>{
                {"C:\\file.txt", MockFileData.NullObject}
            }, "").As<IFileSystem>();
            var pathMock = new Mock<MockPath>(fsMock.Object);
            pathMock.Setup(x => x.DirectorySeparatorChar).Returns('#');
            fsMock.Setup(x => x.Path).Returns(pathMock.Object);
            var fs = fsMock.Object;

            Assert.AreEqual('#', fs.Path.DirectorySeparatorChar);
            pathMock.Verify(m => m.DirectorySeparatorChar, Times.Once);
        }
```

**Comment by vchirikov** [comment]
Hm, thanks.

**Comment by SuperJMN** [comment]
@fgreinacher I've tested your code fragment and it throws here:

```charp
var pathMock = new Mock<MockPath>(fsMock.Object);
```

> Object reference not set to an instance of an object. 
at System.IO.Abstractions.TestingHelpers.MockFileSystem.FixPath(String path, Boolean checkCaps)
   at System.IO.Abstractions.TestingHelpers.MockFileSystem.AddFile(String path, MockFileData mockFile)
   at System.IO.Abstractions.TestingHelpers.MockFileSystem..ctor(IDictionary`2 files, String currentDirectory)
   at Castle.Proxies.MockFileSystemProxy..ctor(IInterceptor[] , IDictionary`2 files, String currentDirectory)
