### ISSUE TITLE
How to safely derive from DirectoryBase or FileBase in netstandard library?

### ISSUE THREAD

**Issue by flidr** [System-IO-Abstractions/System.IO.Abstractions#649]
Hello, I'm developing a netstandard library which uses System.IO.Abstractions. I need to instantiate my own implementation of DirectoryBase and FileBase with just a couple methods, the remaining methods return NotImplementedException.

Then my netstandard library is used from both NetFramework and NetCore applications. Here it comes...since the DirectoryBase has different interface for both platforms I cannot simply derive from it, because I would either miss some methods or override nonexisting methods.

I would like to avoid changing my netstandard library to multitarget library.

My suggestion is to either

1. make the interface the same for both platforms, throwing an exception in runtime
2. include a non abstract "null" implementation for DirectoryBase/FileBase/etc classes, which I can safely derive from, overriding just needed methods.

**Comment by fgreinacher** [comment]
Thanks for the issue! Which version of .NET Standard are you targeting? If you want to support as much API shape as possible just pick .NET Standard 2.1. This library uses multi-targeting to ensure a nice compile-time experience with little to now runtime exceptions and I'm not planning to change this approach.

**Comment by flidr** [comment]
We used to use .NET standard 2.1, for which had really nice compile-time experience crashing at runtime miserably. The only choice so for is to use multi-targetting...
for example
`
public class XyzDirectory : DirectoryBase{
.....
#if NETCOREAPP
        public override IEnumerable<string> EnumerateDirectories(string path, string searchPattern, EnumerationOptions enumerationOptions){
            throw new NotImplementedException();
        }
        ....
#endif
`

**Comment by fgreinacher** [comment]
Yes, currently that's your best choice. I don't plan to add .NET Core targets (see e.g. https://github.com/System-IO-Abstractions/System.IO.Abstractions/issues/583#issuecomment-619586881), instead I will add support for .NET 5 as soon as it's released. This will hopefully make use cases like yours simpler again.
