### ISSUE TITLE
IPath missing GetFullPath(string, string) overload

### ISSUE THREAD

**Issue by devhawk** [System-IO-Abstractions/System.IO.Abstractions#654]
[Path.GetFullPath](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getfullpath) has two overloads, one taking a single string and one [taking two strings](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getfullpath?view=netcore-3.1#System_IO_Path_GetFullPath_System_String_System_String_). IPath is missing the two string parameter version

**Comment by devhawk** [comment]
Note, the two string parameter version appears to be .net core only, as of netcoreapp2.1 and netstandard2.1

**Comment by fgreinacher** [comment]
Thanks for your report!

> Note, the two string parameter version appears to be .net core only, as of netcoreapp2.1 and netstandard2.1

Yes, the implementation would need to be limited to the .NET Standard targets.

**Comment by Ibrahim-Islam** [comment]
I can work on this

**Comment by fgreinacher** [comment]
Added in #657
