### ISSUE TITLE
LayerFS-Like support for MockFileSystem

### ISSUE THREAD

**Issue by LukasGelke** [System-IO-Abstractions/System.IO.Abstractions#660]
**Is your feature request related to a problem? Please describe.**
Suppose I have a CodedUI/Integration-Test-Project, which requires a bunch of nested directories/files to be set up before the tests can start (copied to a common run/test directory). The component(s) being tested reads some of those files, and may write/override the same or other files.
I would like to know which files are written (and whats the new content if so). Also I would want to "recover"/undo files from failed tests.

**Describe the solution you'd like**
A new `MockFileSystem`-Like class, or a Flag in existing classes that:
- mocks all writes (like it already does)
- reading/checking existence/etc? should consider it's own mocked files first, but then also the real file system
- I don't need a "merged traverse / iterate" (yet), if the functions above work

**Describe alternatives you've considered**
- recursively deep-scan the directory twice - before an after the test
  - could be done without a library
  - ugly
  - "lots" of wasted time
- recursively deep-scan the directory once and use MockFileSystem
  - wasted time
- use a run directory copy for every test
  - not feasible for the amount of tests and files needed to be copied as a whole (even though they might not be used) 

**Additional context**
It's a test for a custom company VSIX. The files to be copied/mocked are an entire C#-Solution, using all of the features of said VSIX.

**Comment by fgreinacher** [comment]
That sounds very interesting, thanks for contributing this idea!

Did I get it right that what you want is something like this:

```csharp

var fileSystem = new FileSystem();
fileSystem.File.Create("real.txt");

var overlayFileSystem = new OverlayFileSystem(fileSystem);
Assert.True(overlayFileSystem.File.Exists("real.txt"));

overlayFileSystem.File.Create("virtual.txt");

Assert.True(overlayFileSystem.File.Exists("virtual.txt"));
Assert.False(fileSystem.File.Exists("virtual.txt"));
```

**Comment by LukasGelke** [comment]
That's correct. And to give some more examples:
```cs
fileSystem.File.WriteAllText("real.txt", "abc");
overlayFileSystem.File.WriteAllText("real.txt", "xyz");

Assert.AreEqual("abc", fileSystem.File.ReadAllText("real.txt"))
Assert.AreEqual("xyz", overlayFileSystem.File.ReadAllText("real.txt"))

overlayFileSystem.File.Delete("real.txt");
Assert.False(overlayFileSystem.File.Exists("real.txt"));
Assert.True(fileSystem.File.Exists("real.txt"));
```
The 'layered delete' could be done in different ways (a `bool` in `MockFile`, a singleton, `null`) so not sure whats the 'best'.
And e.g. I don't need an `overlayFileSystem.File.UnDelete()` since one would use a new overlay per test. But in theory it could be done. (But that's obviously specific to OverlayFileSystem, not IFileSystem)

I could also do the implementation myself if you need help.

**Comment by fgreinacher** [comment]
I like this idea a lot. Let me just think a bit whether I want to have it as part of this repo or as a side gig.

**Comment by fgreinacher** [comment]
OK, so I though a bit about this: I'd prefer to provide this in a separate package built outside of this repository. While I think it's a very very good idea, I don't think it's a core concern of the library that I want to maintain over the longer term. 

If you want I could create you a repository within the `System-IO-Abstractions` group with you as primary maintainer. Just give me a quick ping here if you want that.

Thanks again for your detailed samples and explanations!

**Comment by LukasGelke** [comment]
Sorry for responding late. I had to think about it a bit.
While I appreciate the offer, I'm not so keen on being a sole maintainer. I'd still offer to write the initial implementation, but I'm not sure when and if I could then may be able to keep up with (breaking) changes.

**Comment by fgreinacher** [comment]
> Sorry for responding late. I had to think about it a bit.
> While I appreciate the offer, I'm not so keen on being a sole maintainer. I'd still offer to write the initial implementation, but I'm not sure when and if I could then may be able to keep up with (breaking) changes.

Fully understood. I am in the same situation where I can hardly keep up with my all the stuff I'm involved in, and adding this feature would for sure not make it better 😁 

So, if anyone reading this would like to help @LukasGelke starting and maintaining the new project say so and I can support with the bootstrapping a bit!
