### ISSUE TITLE
Do you want to add a ZipArchive unit-test friendly class ?

### ISSUE THREAD

**Issue by ghost** [System-IO-Abstractions/System.IO.Abstractions#662]
**Is your feature request related to a problem? Please describe.**

Current dotnet framework includes a Zip compression classes to create ZipFiles under System.IO.Compression. But, as you can see here:  https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.IO.Compression.ZipFile/src/System/IO/Compression/ZipFile.Create.cs

It relies on Path.GetFullPath, also some of the methods to add ZipEntries from an existing file also uses it. So, it's hard (at least) to unit test your code (avoiding real file system usage...) if it uses these classes to create a zip file.

I've created some method implementations that creates a ZipFile into a MemoryStream and i have some ZipWrapper that uses your IFileSystem to access to files, etc. so, it's unit-testable from memory create a zip file, etc.

**Describe the solution you'd like**

I was thinking if maybe you like/i can do, an implementation of System.IO.Compression in this repository to include also abstraction to Zip/Unzip stuff from an Mockable File System.
What do you think ?

I know i'm a bit obsessed about not using the FileSystem on UnitTesting... but...

**Describe alternatives you've considered**

**Additional context**

The unit tests for ZipFile in dotnet/runtime: https://github.com/dotnet/runtime/blob/master/src/libraries/System.IO.Compression.ZipFile/tests/ZipFile.Create.cs
The zipfile helper they use to have zips: https://github.com/dotnet/runtime/blob/ec26ee542d660d378004633de2eb511d6290a78c/src/libraries/Common/tests/System/IO/Compression/ZipTestHelper.cs#L18 that uses a TempFile class ( https://github.com/dotnet/runtime/blob/ec26ee542d660d378004633de2eb511d6290a78c/src/libraries/Common/tests/System/IO/Compression/ZipTestHelper.cs#L23 ) which uses System.Path internally https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/Common/tests/System/IO/TempFile.cs#L16 .

**Comment by fgreinacher** [comment]
Thanks for writing up your thoughts in detail!

Have you seen https://github.com/System-IO-Abstractions/System.IO.Abstractions/issues/396? We had some discussions in there and decided that the extension-based approach works alright.

What's your opinion on the points there?

**Comment by ppadial** [comment]
@fgreinacher the extenstions method approach looks fine and simple, but, not sure if makes sense having ZipOperations as "operations" of a file system, so for a more architectural solution i guess having some Compression classes looks better to me (like is already for File,Directory, Path, etc).

Anyway, the PR's never happened right? so we need to decide how to implement it.

What do you think?

**Comment by fgreinacher** [comment]
Usually my default for adding new features is "no", so I'd be happy to see some examples that show how your proposal would be better than the extension method-based approach. I'm not too ambitious about making this library architecturally nice, it should really be a super-simple drop-in replacement for `System.IO`.

**Comment by ppadial** [comment]
Ok, let me prepare a PR with samples.

**Comment by a2937** [comment]
Is this enhancement still in the works? I'd like to be able to unit test my zip files too.

**Comment by fgreinacher** [comment]
> Is this enhancement still in the works? I'd like to be able to unit test my zip files too.
> 
> Edit: Did not see that the person who made it is gone.

I currently don't have any plans to add this feature to the core library because I think the [extension-method based approach](https://github.com/System-IO-Abstractions/System.IO.Abstractions/issues/396#issuecomment-436059122) works fine. Have you already tried that @a2937?

**Comment by fgreinacher** [comment]
Closing this issue for the reasons above and because the author of this issue is not on GitHub anymore.

Feel free to comment here if anything is unclear or I oversaw a scenario.
