### ISSUE TITLE
Question: is System.IO.Abstractions supported on Windows on ARM?

### ISSUE THREAD

**Issue by enricogior** [System-IO-Abstractions/System.IO.Abstractions#663]
We are adopting System.IO.Abstractions for PowerToys https://github.com/microsoft/PowerToys/issues/6920, we don't have an ARM version yet, but it's planned and we would like to make sure System.IO.Abstractions is fully supported on ARM.
If anyone can share their experience, it would be great.
Thank you.

**Comment by fgreinacher** [comment]
Thanks for your question. I haven't tried it but I would not expect any problems because there are no native dependencies in here, the core library is mostly "just" forwarding to `System.IO` types.

**Comment by fgreinacher** [comment]
@enricogior Are you able to try it out on a Windows ARM box? Would be great to mention the result of your evaluation here 🥇

**Comment by enricogior** [comment]
@enricogior 
we are not at that point yet, but we will eventually. That's why we are starting to pay attention to any new thing we add to the project since we want to be in good shape for when we will start porting PowerToys to ARM.

**Comment by fgreinacher** [comment]
Ok, thanks for the response! As said above I don't expect any issues on ARM, so I'm closing this issue. Feel free to reopen or create separate bugs in case you run into trouble!
