### ISSUE TITLE
Path.IsPathFullyQualified removed?

### ISSUE THREAD

**Issue by Nezrahm** [System-IO-Abstractions/System.IO.Abstractions#682]
**Describe the bug**
We previously had Path.IsPathFullyQualified and now we seemingly don't.

**Additional context**
Upgraded from System.IO.Abstractions 12.2.26 to 13.2.2

**Comment by fgreinacher** [comment]
Thanks for reporting this regression. What is your target framework?

**Comment by Nezrahm** [comment]
Ah, compiling under net5.0 but tried targeting the dll to both netstandard2.1 and net5.0 with the same result.
