### ISSUE TITLE
Provide static property/singleton for FileSystem

### ISSUE THREAD

**Issue by skrysmanski** [System-IO-Abstractions/System.IO.Abstractions#694]
**Is your feature request related to a problem? Please describe.**

When I use `IFileSystem` in methods, I declare its parameter like this:

```c#
public void MyMethod(..., IFileSystem? fileSystem = null)
```

In this case, `null` means "use the real file system". So, inside the method I need to do something like this:

```c#
(fileSystem ?? s_realFileSystem).File.WriteAllBytes(filePath, bytes);
```

I currently have a shared `FileSystem` instance (`s_realFileSystem`) in my project. 

So I was wondering: Why does System.IO.Abstractions not provide a `static` property/field for a `FileSystem` instance that can be used in this scenario? (Or does it and I could not just find it?)

**Describe the solution you'd like**

To solve this, you could add a property like this to the `FileSystem` class:

```c#
public static FileSystem Instance { get; } = new FileSystem();
```

This way consumers of your library would not have to implement this property themselves (over and over again).

**Comment by fgreinacher** [comment]
Thanks a lot @skrysmanski for the proposal, this is greatly appreciated 👍

I don't want to add this to the core library for the following reasons:

1. the main purpose of this library is to encourage inversion of control and static properties encourage short-circuiting dependency injection
2. exposing a single instance might cause issues in multi-threaded scenarios and I don't have the capacity to support such use cases (I don't think it currently is a problem, but who knows what the future will bring 😀)
3. there is no benefit, except a few less line of codes, in having this property centrally over declaring it in the usage site

**Comment by skrysmanski** [comment]
@fgreinacher 

> the main purpose of this library is to encourage inversion of control and static properties encourage short-circuiting dependency injection

I was "afraid" you would say this. ;) Dependency injection doesn't really work for methods, though. But I can sympathize with your decision (keeping the API clean).

> exposing a single instance might cause issues in multi-threaded scenarios

The same is true for dependency injection (as I'm guessing (some/most) consumers of your library would configure `IFileSystem` to be a singleton).

> there is no benefit, except a few less line of codes, in having this property centrally over declaring it in the usage site

With a central property you don't have redundant "copies" of `FileSystem` in memory anymore.

However, in the end, I'm guessing the whole thing comes down to "gut feeling" and I can see your point-of-view. Thus, I'm closing this issue.
