### ISSUE TITLE
TestingHelpers.MockFileSystem level flags to simulate ReadOnly filesystem and Out-Of-Space conditions

### ISSUE THREAD

**Issue by ericnewton76** [System-IO-Abstractions/System.IO.Abstractions#71]
I was just considering the scenarios where it would be nice to test low-space conditions and unable to write conditions on the filesystem itself.

In theory, (on TestingHelpers.MockFileSystem) a property bool IsReadOnly and probably a MakeReadOnly method to force the filesystem into readonly mode.

In addition, another "testing" flag to force Out-Of-Space type of exceptions.  I realize this could get a bit convoluted, whereby having to keep track of file allocations and byte sizes and so forth, but perhaps an initial "simplistic" version would just bomb on any "new" writes with "OutOfSpaceException" of some sort.

What does everybody else think?

**Comment by bacathey** [comment]
The Helpers are not technically Mocks. They are stubs and should be assumed to behave as such. Be aware that the behavior may not match the behavior expected based on experience with the real implementations. If you need something that is closer in behavior, build it out (and offer up a pull request to contribute back to the library).

Mocking frameworks are great ... :)

**Comment by jpreese** [comment]
Going to consider out of scope for now.
