### ISSUE TITLE
Implementation of File.Open(string,FileMode,FileAccess,FileShare)

### ISSUE THREAD

**Issue by ericnewton76** [System-IO-Abstractions/System.IO.Abstractions#72]
So the implementation currently requests someone to do this.

However, the way that MockFileData and MockFileStream are separated makes this wierd.

MockFileData should change to a file system handle type of class that could keep track of the current mode of a file (this simulates the file system itself managing file handles/read-write locks/etc)

MockFileStream should be the primary holder of data, utilizing its internal MemoryStream's byte[].

**Comment by manne** [comment]
i like your approach. do you already have some code?

**Comment by ericnewton76** [comment]
@manne, i believe somebody started going down this route, it may just need to be finished out.  I haven't looked under the hood right there in a long while

**Comment by jpreese** [comment]
It looks like this method has already been implemented.
