### ISSUE TITLE
Comparison/performance measurement between System.IO.Abstractions versus using ram disk

### ISSUE THREAD

**Issue by tapika** [System-IO-Abstractions/System.IO.Abstractions#722]
`System.IO.Abstractions` is nice way to abstract real file system - I think it works currently only on real file system and tries to abstract it's usage. Ideally I think not only file system should be abstracted, it would be good to have API abstractions between for example archives (zip, 7z, etc...) as simple system approach, or dive into more complex direction - that is mountable file systems (fat, iso, etc...). 

But I think even with current implementation `System.IO.Abstractions` is quite useful if you want to test and mock file system.

Another approach not to use `System.IO.Abstractions`, but use ram disk instead - for example `imdisk` - for example one tutorial exists here: 

https://www.tenforums.com/tutorials/174094-how-create-ram-disk-imdisk-windows-10-a.html

Ram disk is some complex to set-up, but it does not require file system mock up as it's - you can just read and write files on ram disk. But this approach can have some overhead, for example storing other attributes, which file system required - like permissions, file modification times and so on. This overhead could be also considered as "API richness" - eventually file system mock up will not reach all dark corners of file system, or you need to mock them as well (that is file system permissions, file attributes and so on)

Would it be possible to test usage of `System.IO.Abstractions` versus RAM disk (for example `imdisk`) - and compare for example performance and potentially other characteristics (like integration, simplicity of testing, mount / unmount delays, consumed ram) -and write as it's own articles / wiki document about summary of your findings ?

It would be good that created project would be also located on git, as example project (e.g. how you can use imdisk) with performance test framework (in case if `System.IO.Abstractions` or `imdisk` gets improved over time)

**Comment by tapika** [comment]
According this youtube video (sorry - it's in Russian) - guy tried to speed up java gradle builds using ram disk, and
overall build metrics are here:

http://www.youtube.com/watch?v=yIhMQ8y5eG4&t=4m31s

where ram disk is slightly slower than SSD drive  - 55s versus 53s, 

but faster in case of incremental builds:

http://www.youtube.com/watch?v=yIhMQ8y5eG4&t=5m10s - 22s versus 25s.

But I think usage of `System.IO.Abstractions` versus ramdisk is not so relevant if test framework does not use huge amount of file operations - like it's with some packaging / uncompression tools.

Most people probably will choose not to use `System.IO.Abstractions` and not to use ram disk, but those who actually needs it - time difference is quite small to conclude to one or another alternative - then in this case API richness and usability might influence the decision.

**Comment by fgreinacher** [comment]
Hey @tapika, thanks for your thoughts!

To be honest I'm not fully sure what you're asking for here? `System.IO.Abstractions` is meant as a dumb abstraction layer of existing file system APIs. There are several old issues asking for add-on functionality and/or higher level abstractions, e.g. https://github.com/System-IO-Abstractions/System.IO.Abstractions/issues/660, https://github.com/System-IO-Abstractions/System.IO.Abstractions/issues/604, or https://github.com/System-IO-Abstractions/System.IO.Abstractions/issues/473. While I totally agree that such things are useful they should not be here in the core library.

If you're asking for some document that compares the mock file system provided by this project with a Ramdisk-based approach, feel free to do so. I'll happily add a link to our documentation here. But again, this is not something that I see in scope of this package and/or myself as the maintainer.

**Comment by fgreinacher** [comment]
Closing this issue. Feel free to reopen/update here if you have additional input 👍
