### ISSUE TITLE
Discrepancy of MoveTo() when only changing case.

### ISSUE THREAD

**Issue by soi013** [System-IO-Abstractions/System.IO.Abstractions#737]
**Describe the bug**

When only changing case, (ex: abc.txt -> ABC.txt) `System.IO.Abstractions.TestingHelpers.MockFileInfo.MoveTo()` throw an IOException but `System.IO.Abstractions.FileInfoWrapper.MoveTo()` and `System.IO.FileInfo.MoveTo()` do not throw.

**To Reproduce**

```csharp
//System.IO.FileInfo.MoveTo()
string targetFilePath = @"D:\TestZone\abc.txt";
string renamedFilePath = @"D:\TestZone\ABC.txt";
File.WriteAllText(targetFilePath, "abc");
var dotNetFile = new FileInfo(targetFilePath);
dotNetFile.MoveTo(renamedFilePath);
File.Delete(renamedFilePath);

//System.IO.Abstractions.FileInfoWrapper.MoveTo()
var realFileSystem = new FileSystem();
realFileSystem.File.WriteAllText(targetFilePath, "abc");
var realFile = realFileSystem.FileInfo.FromFileName(targetFilePath);
realFile.MoveTo(renamedFilePath);
realFileSystem.File.Delete(renamedFilePath);

//System.IO.Abstractions.TestingHelpers.MockFileInfo.MoveTo()
var mockFileSystem = new MockFileSystem(new Dictionary<string, MockFileData>()
{
    [targetFilePath] = new MockFileData("abc"),
});
var mockFile = mockFileSystem.FileInfo.FromFileName(targetFilePath);
mockFile.MoveTo(renamedFilePath);
```

The last line throw an `IOException(The file D:\TestZone\ABC.txt already exists.)`.

**Expected behavior**
Not throw Exception.

**Additional context**

This is an aside, but `System.IO.DirectoryInfo.MoveTo()` throw `IOException(Source and destination path must be different)` in same case.

**Comment by hangy** [comment]
Should it always throw an Exception? On *nix (or rather some filesystems where case matters ), such a rename operation probably should be possible.

**Comment by soi013** [comment]
> Should it always throw an Exception?

No.

Case only renaming is allowed on all operating systems (Windows, Mac, *nix).
What only *nix can do is to include filenames in the same directory that differ only in case.

**Comment by fgreinacher** [comment]
Thanks for reporting!
