### ISSUE TITLE
MockDirectory.GetDirectories does not handle empty searchOption properly

### ISSUE THREAD

**Issue by TureeZhang** [System-IO-Abstractions/System.IO.Abstractions#739]
**Describe the bug**
Directory.GetDirectories(path,pattern,searchOption) returns nothing when the 3rd parameter use SearchOption.TopDirectoryOnly, just like this ``Directory.GetDirectories(@"F:\BeflamRule\src\Beflam.Rule.WebApi\bin\Debug\netcoreapp3.1\ProjectResource", "", SearchOption.TopDirectoryOnly)``

**To Reproduce**

1. copy these code bellow which I just writed in my unit test to create the mock files and directories

```c#
string projResoRoot = Path.Combine("F:\BeflamRule\src\Beflam.Rule.WebApi\bin\Debug\netcoreapp3.1\ProjectResource", "my-project");
            string projectFile1 = Path.Combine("F:\BeflamRule\src\Beflam.Rule.WebApi\bin\Debug\netcoreapp3.1\ProjectResource", "__node__info__file__");
            string projectFile2 = Path.Combine("F:\BeflamRule\src\Beflam.Rule.WebApi\bin\Debug\netcoreapp3.1\ProjectResource", "my-project", "Biz/Rule", "__node__info__file__");
            string projectFile3 = Path.Combine("F:\BeflamRule\src\Beflam.Rule.WebApi\bin\Debug\netcoreapp3.1\ProjectResource", "my-project", "Biz/Rule", "Models.vl.json");
            string projectFile4 = Path.Combine("F:\BeflamRule\src\Beflam.Rule.WebApi\bin\Debug\netcoreapp3.1\ProjectResource", "my-project", "Biz/Rule", "Consts.cl.json");
            string projectFile5 = Path.Combine("F:\BeflamRule\src\Beflam.Rule.WebApi\bin\Debug\netcoreapp3.1\ProjectResource", "my-project", "Biz/Rule", "MyRule.rs.json");
            MockFileSystem mockFileSystem = new MockFileSystem(new Dictionary<string, MockFileData> {
                { projResoRoot, new MockDirectoryData()},
                { projectFile1, new MockFileData("") },
                { projectFile2, new MockFileData("{\"Name\":\"my-project\",\"_dataDic\":{}}") },
                { projectFile3, new MockFileData("{\"Name\":\"/my-project/Models.vl.json\",\"_dataDic\":{}}") },
                { projectFile4, new MockFileData("{\"Name\":\"/my-project/Consts.cl.json\",\"_dataDic\":{}}") },
                { projectFile5, new MockFileData("{\"Name\":\"/my-project/MyRule.rs.json\",\"_dataDic\":{}}") }
            });
```

2. it's create these files and directories :

![image](https://user-images.githubusercontent.com/30072809/125223135-d39fca80-e2fd-11eb-86a6-5d60776dc66c.png)

3. call the method ``mockFileSystem.Directory.GetDirectories(@"F:\BeflamRule\src\Beflam.Rule.WebApi\bin\Debug\netcoreapp3.1\ProjectResource", "", SearchOption.TopDirectoryOnly)``

4. it returns nothing, but should be "my-project" directories under "F:\BeflamRule\src\Beflam.Rule.WebApi\bin\Debug\netcoreapp3.1\ProjectResource".

![image](https://user-images.githubusercontent.com/30072809/125224204-bb30af80-e2ff-11eb-8d85-ab61355b666a.png)

**Expected behavior**

it should be "my-project" directory under "F:\BeflamRule\src\Beflam.Rule.WebApi\bin\Debug\netcoreapp3.1\ProjectResource", just like ``System.IO.Directory.GetDirectories(@"F:\BeflamRule\src\Beflam.Rule.WebApi\bin\Debug\netcoreapp3.1\ProjectResource", "", SearchOption.TopDirectoryOnly)`` did . 

The path "F:\BeflamRule\src\Beflam.Rule.WebApi\bin\Debug\netcoreapp3.1\ProjectResource" also really exist on my computer disk which now contians "t1" "t2" directories ,System.IO.Directories works right :

![image](https://user-images.githubusercontent.com/30072809/125224261-db606e80-e2ff-11eb-8b8f-7bd830379a54.png)

**Additional context**

Nothing else . GOOD JOB man, nice unit test utils, thanks so much !

**Comment by TureeZhang** [comment]
I found the problem is **Pattern parameter**, when I use ``"*"`` mockFileSystem works right ,but failed when use ``""``.

![image](https://user-images.githubusercontent.com/30072809/125226419-a229fd80-e303-11eb-979b-65303f9db49d.png)

but System.IO.Directory support also ``""`` and ``"*"``.

**Comment by fgreinacher** [comment]
> I found the problem is **Pattern parameter**, when I use `"*"` mockFileSystem works right ,but failed when use `""`.
> 
> ![image](https://user-images.githubusercontent.com/30072809/125226419-a229fd80-e303-11eb-979b-65303f9db49d.png)
> 
> but System.IO.Directory support also `""` and `"*"`.

Great analysis, thanks for that @TureeZhang!

So we need to fix the implementation of `MockDirectory.GetDirectories` to treat an empty search pattern as "match-anything".

I'll mark this as ready in case you or somebody wants to pick it up!
