### ISSUE TITLE
MockFileSystem supporting both Windows & Linux paths?

### ISSUE THREAD

**Issue by jacekard** [System-IO-Abstractions/System.IO.Abstractions#754]
Hello, I'd like to know if it's possible to write Unit Tests for both Windows and Linux without checking OSPlatform in the runtime.
Currently paths like "c:\" and "/home" are correctly generated on Windows, but the same Tests are crashing when executed in Linux environment.

Thanks for the tips!

**Comment by fgreinacher** [comment]
Yes, you can use `MockUnixSupport.Path()` to create paths in a platform neutral way. Alternative using relative paths that you build via `Path.Combine` is also possible.

https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/main/tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileAppendAllLinesTests.cs#L15

**Comment by jacekard** [comment]
Thanks! I'll try that.
